### ISSUE TITLE
Option for emulated OPL2/3-based FM synthesis MIDI playback

### ISSUE THREAD

**Issue by JPLeBreton** [luciusDXL/TheForceEngine#102]
This seems squarely in "nice to have, down the road" territory. Most people playing Dark Forces back in 1995 didn't have a wavetable MIDI card like the Roland MT-32, they more likely had a Sound Blaster compatible card with an OPL3 FM synth chip. Projects like GZDoom incorporate an emulator for these chips to offer that unique sound for MIDI music. It's possible some Dark Forces mods had MIDI composed more with that sound in mind than what you'd hear in the modern era, so there's also an authenticity argument.
It'd be a nice (non-default, to be clear) option to have in the music options section.

**Comment by luciusDXL** [comment]
Implemented in version 1.09.
