### ISSUE TITLE
[Feature Request] Disable head bobbing

### ISSUE THREAD

**Issue by RoyBatty64** [luciusDXL/TheForceEngine#106]
These effects always give me headache, would be great if we could disable it.

**Comment by Dzierzan** [comment]
It is already in the DOS game and TFE has it too. It is one F keys which disables that.

**Comment by luciusDXL** [comment]
Go to the settings/configuration window, then Input. There you can see what function key this is assigned to. If you press the key during gameplay you should see a message that "head wave" has been disabled (or something like that).

**Comment by RoyBatty64** [comment]
Oh, my CD doesn't have any kind of manual, just an insert. Thank you.

**Comment by luciusDXL** [comment]
It sounds like you want a separate toggle to allow for weapon sway but no headbob?

**Comment by RoyBatty64** [comment]
Yes, exactly.

**Comment by TP555** [comment]
Hi

 @RoyBatty64

F6 Disable Weapon Sway like Wolf3D !
Works for both Dos , TFE  !

**Comment by AAS** [comment]
@luciusDXL Could you please add it to the settings menu so that you can turn it off permanently?

**Comment by luciusDXL** [comment]
There is now an accessibility option for this in master. It will be available in the next release.
