### ISSUE TITLE
`SOUND.GOB` incompatible?

### ISSUE THREAD

**Issue by siredmar** [luciusDXL/TheForceEngine#107]
I have no idea if this is linux specific or my version of Dark Forces (from year 199?).
So i've created an issue in gilmorem560's fork which contains the linux port.

https://github.com/gilmorem560/TheForceEngine/issues/3

**Comment by luciusDXL** [comment]
I just want to clarify that I believe this is an issue with TFE on Linux, but sounds do work on Windows. I am not planning on spending a lot of time on Linux and Mac support until version 1.0 is released. You can raise the issue in gilmorem560's fork, but he already mentioned that sound does not work, so it may have to wait until then.

**Comment by luciusDXL** [comment]
See https://theforceengine.github.io/Roadmap.html for more information.
