### ISSUE TITLE
[Bug] Item Pickup messages scale incorrectly at high resolutions

### ISSUE THREAD

**Issue by OpenRift412** [luciusDXL/TheForceEngine#114]
Gave the port a download today, love the work so far! I will say though I noticed something a bit weird about the item pickup text that usually appears in the top-left. Unlike the rest of the HUD, it's scaled in square pixels, while the rest of the HUD is scaled with the typical 1:1.2 pixel ratio that all 320x200 DOS games use. 

Here's some screenshots comparing 200p to 1080p:

200p (how it's supposed to look)
![image](https://user-images.githubusercontent.com/29780788/169219109-a376c374-d9dc-4a04-b7c4-5068b8717b48.png)

1080p (incorrect scaling)
![image](https://user-images.githubusercontent.com/29780788/169218942-a53230d3-499c-496f-ad12-157e09cbefc5.png)

**Comment by luciusDXL** [comment]
Fixed in version 0.94.000-11-g5b56a8a3.
