### ISSUE TITLE
Crash in Linux - using Windows exe via Wine/Proton

### ISSUE THREAD

**Issue by bangstk** [luciusDXL/TheForceEngine#116]
Hello,
Using 0.91 Bug Fix Release 6 from the website.

Using Wine/Proton to run Force Engine on Linux (specifically, Steam Deck) results in a crash dialog right 
when hitting the Force Engine main menu

"SEH Exception"

However, if you ignore the crash message and click back into the game (without clicking Ok in the crash dialog), you can still keep playing it, just without any sound effects (music works)
Therefore I would guess the crash is in the sound system somewhere.

Naturally a native linux build would be ideal, but perhaps whatever is causing this crash in Wine/Proton can be a quick fix.

I can't attach the dump as a .dmp so rename it from .txt to .dmp.

[the_force_engine_log.txt](https://github.com/luciusDXL/TheForceEngine/files/8894151/the_force_engine_log.txt)
[crashdump.dmp.txt](https://github.com/luciusDXL/TheForceEngine/files/8894170/crashdump.dmp.txt)

**Comment by bangstk** [comment]
I had music because I have installed QSynth onto my steam deck, and with that music does work.
Normally Steam Deck has no MIDI synthesizer installed by default.

**Comment by neytjs** [comment]
Yes, I have encountered the same problem on Linux too.

**Comment by luciusDXL** [comment]
There is more work to be done to get audio working in Linux. I plan on focusing on official Linux support soon after version 1.0 releases.

**Comment by ViewtifulCereza** [comment]
Hi,

sorry for hijacking this thread, but I have problems browsing the executable since it's in a hidden folder (.steam) but I can't see how to show hidden files from the menu selecting the path/executable. Any clues?

**Comment by DuendeInexistente** [comment]
> Hi,
> 
> sorry for hijacking this thread, but I have problems browsing the executable since it's in a hidden folder (.steam) but I can't see how to show hidden files from the menu selecting the path/executable. Any clues?

It's a wine setting, go to the drives tab in winecfg and enable show dot files.

**Comment by luciusDXL** [comment]
Now that Linux is officially supported, I am closing any Wine related issues.
