### ISSUE TITLE
Settings location

### ISSUE THREAD

**Issue by Wronschien** [luciusDXL/TheForceEngine#119]
Hello, where are the settings stored ? I searched everywhere I could think of, obviously not in the right place though.

**Comment by TP555** [comment]
Hi

c:\Users\All Users\TheForceEngine\  for Savegame and Temp Files  !
c:\Users\Thomas\Documents\TheForceEngine\ Config File etc.   !

Cheers  !

**Comment by Wronschien** [comment]
Ah great, thanks for the reply !
