### ISSUE TITLE
The joystick is quite difficult to use

### ISSUE THREAD

**Issue by aybe** [luciusDXL/TheForceEngine#121]
Tested with an Xbox One controller,

It would be great if,

- there was the ability to have per axis sensitivity, i.e. for a lower sensitivity on right stick Y for looking
- the implementation of good dead zones, it is almost impossible to walk forward and not strafe at the same time

Other than that, thank you for such great engine 👍🎯💯😀

**Comment by luciusDXL** [comment]
The controller input supports per-axis sensitivity and deadzones have been improved since this request.

**Comment by aybe** [comment]
Nice, thanks! 😁
