### ISSUE TITLE
[Feature Request] Internal Midi playback support with SoundFont by FluidSynth.

### ISSUE THREAD

**Issue by ni1chigo2115** [luciusDXL/TheForceEngine#122]
TFE music is output in Midi, but Windows standard only has a poor MidiMapper, and I use a special version of Timidity for hi-def quality, which is heavy and cumbersome to configure.
I think the combination of FluidSynth and SoundFont could easily implement remastered Midi playback.

This is also implemented in GZDooM and is very useful as a way to improve the sound quality of midi with less load.

**Comment by gilmorem560** [comment]
Sorry, been totally mentally checked out from this for a while. Glad to see interest is still here. I never got very far with playing with the sound stuff at the time. The audio library here is RtAudio. I'm not sure if that has its own built-in mechanism for emulating MIDI, but if you haven't played with that yet, their docs are probably the best place to start for implementing universally-operational MIDI. Based on some of your commentary though, sounds like you're on the right track.

I wonder if this would require forking FluidSynth from the parent TFE process. That should pass it open file descriptors and such, which I *think* would be way to go to prevent the processes from blocking each other. That said, I have little direct experience playing with Alsa PCM calls.

The other thing you might consider is iirc RtAudio had a number of backends available on *NIX, Alsa being just one of them. PulseAudio was in there methinks, that may also offer some means to multiplex the audio hardware to offload MIDI emulation to FluidSynth. Not sure, audio is a realm I haven't experimented in nearly as much as systems stuff and GPU/acceleration.

Best of luck. Happy to get dragged/atted into any of this stuff if further *NIX work starts in earnest. My chief interest in being involved in such a process would be to keep it generic, avoid Linux-isms, with the goal that the UNIX aspects introduced would adhere to POSIX and therefore simplify the rollout to basically all non-Windows platforms. I'm using Linux these days but I was running FreeBSD as a main driver at the time I was tinkering on this (I'm pretty sure...I'm a bit nomadic with my operating environments). In any case, excited to see this continue to grow!

**Comment by spacekomet** [comment]
Thanks for reply, @gilmorem560 and for the time invested into preparing linux fixes.

I actually manage to make it work, the music and the sound effects. 
Based on your [Makefile](https://github.com/gilmorem560/TheForceEngine/blob/linux_port_implementation/Makefile) only support for ALSA is getting compiled, therefore I simply added -D__LINUX_PULSE__ into the Makefile  and compiled it again. 
Sound effects work correctly  now out of the box. And the music started to play when I first run the 
`fluidsynth --server -a alsa -m alsa_seq -v /usr/share/soundfonts/FluidR3_GM.sf2`
(it also works with -a pulseaudio )  and then start the game. 

Fyi: I'm using up to date Manjaro with all necessary dependencies installed, including Pulseaudio of course and with rtaudio 5.2.0  and rtmidi 5.0.0.

**Comment by QmwJlHuSg9pa** [comment]
In terms of accuracy to original hardware (Roland), it's probably better to utilise Munt over Timidity. Granted, Munt requires ROM files, rather than a SF2 file.

Projects like DOSBox Staging and SCUMMVM have even integrated mt32emu directly into their builds.

**Comment by spacekomet** [comment]
I wonder what are those soundfonts here: https://github.com/luciusDXL/TheForceEngine/tree/master/TheForceEngine/SoundFonts

**Comment by luciusDXL** [comment]
Sound Fonts are now supported in version 1.09 (though not using Fluidsynth).
