### ISSUE TITLE
[Feature Request] UTF8-standard cut-scene subtitles that can be edited by individuals.

### ISSUE THREAD

**Issue by ni1chigo2115** [luciusDXL/TheForceEngine#123]
It will need to be done by hand, but the subtitles will allow non-English native speakers to follow the story.
Multi-language would be better, but not forced, but optional.
...It would be even easier to spread the word if the game font and content could be localized as well.

**Comment by luciusDXL** [comment]
This was added in version 1.09.4 - though it is still in Beta.
