### ISSUE TITLE
hardware renderer: sprites showing through geometry

### ISSUE THREAD

**Issue by MamiyaOtaru** [luciusDXL/TheForceEngine#125]
Visible in a couple places in Research Facility.  Doesn't happen with software renderer.

Before coming out of the air vent, and after exiting the locked front door to the base

![tfeClipping](https://user-images.githubusercontent.com/2042826/197436021-0eb6f11e-65f7-40bc-9d1e-47c6d3c6952d.jpg)

![tfeClipping2](https://user-images.githubusercontent.com/2042826/197436435-b2b1864b-1365-49f5-9079-f87836e3af9f.png)

also here: shot the trooper before I took a screenshot, but his dropped gun still shows it:

![tfeClipping3](https://user-images.githubusercontent.com/2042826/197436673-a4975bd0-6801-4a1b-958b-f2b21a7db624.png)

**Comment by luciusDXL** [comment]
This is fixed in the latest release.
