### ISSUE TITLE
[GPU Renderer] Infrared Goggles do not illuminate dark sectors

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#126]
![Screenshot 2022-10-27 23-18-15](https://user-images.githubusercontent.com/19301383/198495486-de7e3258-8c1a-4c89-a91b-7f72fbcde89d.png)

While the palette is applied to the screen, the sector still appears dark and have to use the headlight just to illuminate and expose the player's presence to enemies.

Also the headlight does not work together with the goggles in DOS where you can brighten the sectors and make it easier to see in the dark. But this works in both the CPU and GPU Renderers. Can we keep this behavior as an optional gameplay flag?

**Comment by luciusDXL** [comment]
Fixed in the latest release.
