### ISSUE TITLE
[GPU Renderer] Imperial City Searchlights rendering the sky instead of surroundings

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#128]
Version 0.92

Caught this on my stream
![Screenshot 2022-10-30 20-55-56](https://user-images.githubusercontent.com/19301383/198911410-be6be2a9-0937-48d9-b07c-629fc90e0545.png)

**Comment by luciusDXL** [comment]
Fixed in build 0.92.000-3-g9d01b27
