### ISSUE TITLE
[GPU Renderer] Imperial City ISB Building HOM

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#129]
Version 0.92

Also caught on my stream

![Screenshot 2022-10-30 21-02-39](https://user-images.githubusercontent.com/19301383/198911748-d80ac5e3-eb3e-4789-8e87-7bd21e307997.png)

**Comment by luciusDXL** [comment]
Fixed in build 0.92.000-3-g9d01b27
