### ISSUE TITLE
Random Freeze !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#130]
Hi

I have with Version 0.92.000-3-g9d01b27 some Random Freezes , i had Wait for longer , but no Chance  , complete Lock up , and the Task Manager says : TheForceEngine.exe (Inactive) , Music still Playing Normal  !
Yesterday i had the same problem  !

I don't know if it cause with GPU or Software Mode because it very Random !
Error Log will not Created !

That is the last from the_force_engine_log.txt , before it Freeze  !

[Main] The Force Engine
v0.92.000-3-g9d01b27

[Paths] Program Path: "n:\The Force Engine\"
[Paths] Program Data: "C:\ProgramData\TheForceEngine\"
[Paths] User Documents: "C:\Users\Thomas\Documents\TheForceEngine\"
[Paths] Source Data: "N:/The Force Engine/Games/Dark Forces/"
[Startup] TFE_System::init
[Display] Fullscreen enabled.
[Display] Vertical Sync enabled.
[RenderBackend] OpenGL Device Tier: 3
[Startup] TFE_AudioSystem::init
[Startup] TFE_MidiPlayer::init
[Startup] TFE_Polygon::init
[Startup] TFE_Image::init
[Startup] TFE_FrontEndUI::init
[MemoryRegion] Allocated new memory block in region 'game' - new size is 1 blocks, total size is '8388608'
[MemoryRegion] Allocated new memory block in region 'level' - new size is 1 blocks, total size is '8388608'
[Progam Flow] The Force Engine Game Loop Started
[Game] Dark Forces Version: 1.0 (Build 1)
[MemoryRegion] Allocated new memory block in region 'Landru' - new size is 1 blocks, total size is '4194304'
[MemoryRegion] Allocated new memory block in region 'Cutscene' - new size is 1 blocks, total size is '8388608'
[Landru Music] Set Seq 1...
[Player] Setting up level 'SECBASE'
[Warning : level_loadGeometry] Could not open 'ZWIMP10L.BM', using 'default.bm' instead.
[Warning : level_loadGeometry] Could not open 'ZWIMP11.BM', using 'default.bm' instead.
[Error : level_loadINF] Hit the end of INF 'SECBASE' before parsing all items: 58/60
[MemoryRegion] Allocated new memory block in region 'game' - new size is 2 blocks, total size is '16777216'
[MemoryRegion] Allocated new memory block in region 'game' - new size is 3 blocks, total size is '25165824'
[MemoryRegion] Allocated new memory block in region 'game' - new size is 4 blocks, total size is '33554432'
[Music] trans4=10...
[Music] entry2=3...

Settings:

[Window]
x=0
y=32
width=2560
height=1080
baseWidth=1280
baseHeight=720
fullscreen=true
[Graphics]
gameWidth=2880
gameHeight=2160
widescreen=true
asyncFramebuffer=true
gpuColorConvert=true
colorCorrection=false
perspectiveCorrect3DO=false
extendAjoinLimits=true
vsync=true
brightness=1.000
contrast=1.000
saturation=1.000
gamma=1.000
reticleEnable=true
reticleIndex=6
reticleRed=0.250
reticleGreen=1.000
reticleBlue=0.250
reticleOpacity=1.000
reticleScale=1.000
renderer=1
skyMode=1
[Hud]
hudScale="Proportional"
hudPos="Edge"
scale=1.000
pixelOffsetX=0
pixelOffsetY=0
[Sound]
soundFxVolume=0.750
musicVolume=1.000
cutsceneSoundFxVolume=0.900
cutsceneMusicVolume=1.000
use16Channels=true
[Game]
game="Dark Forces"
[Dark_Forces]
sourcePath="N:/The Force Engine/Games/Dark Forces/"
emulatorPath=""
airControl=0
fixBobaFettFireDir=false
disableFightMusic=false
enableAutoaim=false
pitchLimit=3
[Outlaws]
sourcePath="c:/games/steam/SteamApps/common/outlaws/"
emulatorPath=""
[CVar]

I had Check all Game Data , and TFE Files , is all ok
DF Version : German

**Comment by luciusDXL** [comment]
I believe this is fixed in version 0.93. It can be re-opened if it happens again.
