### ISSUE TITLE
Quick Save + Reshade = Freeze !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#131]
Hi

i saw some problems with Quicksave and Reshade 5.5.0 , the Game Freeze , but i can play and hear Sounds , seems like a Overlay Problem , Quick Load Works
i had try also with older Reshade 5.4.2 , and of course with no Filters ,  but is the Same  !

Tested Version : 0.93.000-14-g80f9ca12

I hope you wan't keep the Support with Reshade and TFE !

Update and 1.0

Reshade 5.5.2 works better now TFE + Quicksave
Just Press ESC  , when it Freeze , the Game will Response again  :D

Update2:
It can full fixed the Freeze , only when OBS Studio is running , no Recording/Streaming needed  !

**Comment by luciusDXL** [comment]
I don't plan on fixing Reshade specific issues.
