### ISSUE TITLE
[GPU Renderer] Render bug HOM in Jabba's Ship

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#133]
Build: v0.93.000-27-gb2c03e72
Game: Dark Forces
Renderer: Classic (Hardware)
On Jabba's Ship at these coordinates the geometry shimmers and causing a rendering bug with a HOM that does not appear in DOS

<img width="1280" alt="Screenshot 2022-11-27 02-02-38" src="https://user-images.githubusercontent.com/19301383/204123625-5642102a-75d0-4a3e-9675-20fa55e37dc2.png">

**Comment by luciusDXL** [comment]
Fixed in version 0.94.000-35-ge74b3249.
