### ISSUE TITLE
[GPU Renderer] Executor window viewing sky, not the sector showing the smuggler ship

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#134]
Build: v0.93.000-27-gb2c03e72
Game: Dark Forces
Renderer: Classic (Hardware)
Looking out the viewport of the hanger bay where the smuggler ship is shows the sky rather than the hanger holding the smuggler ship.

<img width="1280" alt="Screenshot 2022-11-27 02-47-03" src="https://user-images.githubusercontent.com/19301383/204124700-f12be68e-ede6-49dd-ab82-951f62b449ae.png">

**Comment by luciusDXL** [comment]
Fixed in version 94.000-31-gaef577f5.
