### ISSUE TITLE
Game interface in other languages (example: Spanish) are moved so buttons are not detected well

### ISSUE THREAD

**Issue by iagofg** [luciusDXL/TheForceEngine#137]
This is spanish screen:
![image](https://user-images.githubusercontent.com/553739/206906963-7deff8eb-53bb-4f8d-b5a1-50718676b586.png)
And this is english one:
![image](https://user-images.githubusercontent.com/553739/206907055-5cad4a5e-ff87-45eb-be75-231338e53fae.png)
In spanish buttons are on the top-left edge although in english are more centered. When spanish game is executed buttons appear on one position and button click areas are where english ones, so it works wrong.

**Comment by luciusDXL** [comment]
I never understood why they moved the art around like this. But I am planning on modifying the menu to compute the bound area from the art, which should solve this issue for all languages.

**Comment by luciusDXL** [comment]
This should be fixed in **Release Candidate 1**, but I have not been able to test thoroughly so re-open if it still happens for you.
