### ISSUE TITLE
Use mode for detecting background color when rendering cylinder background and make a gradient

### ISSUE THREAD

**Issue by iagofg** [luciusDXL/TheForceEngine#138]
When rendering cylinder background on topmost area instead of the cylinder a solid color is rendered. The problem is that on some levels that background color is NOT the background color (on the example image it should be darker). Use a fixed per-level color or the mode (most frequent color on the background image for detecting the background color from the background image. Also adding a small gradient to solid color in the topmost part of the background image should help to make it more seamless.
This is how is seen currently:
![image](https://user-images.githubusercontent.com/553739/206908024-a9a4bcf8-a1e0-47b3-9698-afa4096ec909.png)
For illustration, this is how it should look after modifications:
![image](https://user-images.githubusercontent.com/553739/206908335-306dbd89-5582-4558-a055-7ea7f065efb1.png)

**Comment by luciusDXL** [comment]
I do plan on revisiting the sky rendering and better color choices. But not until after version 1.0.

**Comment by luciusDXL** [comment]
The sky rendering itself is unlikely to be changed at this point. Instead I will add more options for custom skies in the future.
