### ISSUE TITLE
Add VR support

### ISSUE THREAD

**Issue by iagofg** [luciusDXL/TheForceEngine#139]
Maybe is factible including VR support: check this OpenVR Steam example: it uses OpenGL and SDL just like TheForceEngine https://github.com/ValveSoftware/openvr/blob/master/samples/hellovr_opengl/hellovr_opengl_main.cpp

**Comment by luciusDXL** [comment]
VR support is planned in the future.

**Comment by luciusDXL** [comment]
It looks like someone else is implementing this. And even if that fails, something like this won't happen before Outlaws support is done. So closing for now.
