### ISSUE TITLE
Feature: Borderless window mode

### ISSUE THREAD

**Issue by Alexbeav** [luciusDXL/TheForceEngine#143]
Hello, this is a feature request for adding Borderless Window support. Currently in 0.94-38 there are only Fullscreen/Windowed options.

**Comment by luciusDXL** [comment]
In TFE, fullscreen is always a borderless fullscreen window. In Windows 10+ this turns off the compositor and runs at near maximum speed. TFE does not change your video mode, it simply uses the current desktop mode.
