### ISSUE TITLE
TFE not correctly detecting path to steam install of DF

### ISSUE THREAD

**Issue by anpilley** [luciusDXL/TheForceEngine#145]
I have two steam game installation folders. One in c:\games\steam and the other in d:\games\steam on two separate drives.. Dark forces was installed to d:\games\steam\steamapps\common\Dark Forces\Game for disk-space reasons.

When I first run TFE, it picked the wrong steam folder, despite filling in the rest of the path to the game, and as a result, crashed when I hit start. It took a few minutes to realize it'd chosen the wrong drive despite having the rest of the path more or less correct.

Additionally, the pre-filled forward slashes for path separators don't translate properly on windows and so just switching the drive doesn't work, those need to be switched out for backslashes as well if you're going to auto-detect it.

[the_force_engine_log.txt](https://github.com/luciusDXL/TheForceEngine/files/10262005/the_force_engine_log.txt)

It's not a huge issue (apart from the crash), browsing for the correct location worked once I realized.

**Comment by DamnBriggsy** [comment]
I'm encountering this as well, though I have many steam library folders across multiple drives. It's chosen 'c:/program files (x86)/steam/SteamApps/common/dark forces/Game/', but the game is not installed there.

**Comment by luciusDXL** [comment]
Thanks for the report. For now manually setting up the path works but this should be fixed. :)

**Comment by luciusDXL** [comment]
Fixed in version 1.01.
