### ISSUE TITLE
[Bug/Oversight] 'Walk Slowly' doesn't work when bound to ALT

### ISSUE THREAD

**Issue by OpenRift412** [luciusDXL/TheForceEngine#146]
I suspect this may have to do with ALT being used as one of the shortcut combo keys, but as it stands I can't seem to use ALT as my 'Walk Slowly' key.

**Comment by luciusDXL** [comment]
That is definitely a bug, thanks.

**Comment by SirYodaJedi** [comment]
I don't think ALT works, period. I usually bind crouch to Left Alt, but I can't crouch if crouch is bound to that key.

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
