### ISSUE TITLE
[Bug] Music Plays Slowly in Sound Options Menu

### ISSUE THREAD

**Issue by OpenRift412** [luciusDXL/TheForceEngine#147]
As the title suggests, the music seems to start playing extra slow when navigating to the Sound section of the menu. Switching to a different settings menu causes things to speed back up.

**Comment by luciusDXL** [comment]
Weird, I will take a look.

**Comment by TP555** [comment]
Hi

Can't reproduce this !

Try set OpenGL/GPU , may you use Software Mode + 2160p Upscaler Ingame , which is much CPU Intensive !

You test this with a Special Mission , which  ?
No Problems with the Music from Secbase  !

**Comment by luciusDXL** [comment]
This is outdated, so I'm going to close.
