### ISSUE TITLE
[Feature] Game-matching Settings menus

### ISSUE THREAD

**Issue by OpenRift412** [luciusDXL/TheForceEngine#148]
I think it would be nice to have the settings menus fit more of Dark Forces's theme, using the text sprites and menu graphics from the base game. Is this planned at all?

**Comment by luciusDXL** [comment]
Given the future support for Outlaws, I decided against themed menus for the System UI. I do think adding theming support to the UI would nice, however, as an option.

**Comment by OpenRift412** [comment]
I see. Well how about after Outlaws is fully implemented?

**Comment by Dzierzan** [comment]
There are no ready UI bits to use. You would have to make them from scratch. Considering that TFE will support Outlaws as well, having one generic UI for both games seems like a good idea to keep.

**Comment by luciusDXL** [comment]
I'm going to close this, I'm not planning on having a game-specific system UI. That said, I am planning on adding "skinning" support for the UI in the future, so modders could achieve something similar.

**Comment by OpenRift412** [comment]
> I'm going to close this, I'm not planning on having a game-specific system UI. That said, I am planning on adding "skinning" support for the UI in the future, so modders could achieve something similar.

Question about this "skinning" capability: will modders be able to adjust the layout with their skins or will it just be like assets that replace the blue blocks and fonts?
