### ISSUE TITLE
[Feature] Selectable Windows MIDI output

### ISSUE THREAD

**Issue by Bloodbat** [luciusDXL/TheForceEngine#151]
It would be great to be able to select which MIDI output the engine uses. I suspect it's using Windows' general MIDI and for those of us with other available synths the music sound rather... weak.

**Comment by codengine** [comment]
I would also highly anticipate that feature. In fact that was the only thing that kept me from using this over dosbox

**Comment by codengine** [comment]
I created a PR here: https://github.com/luciusDXL/TheForceEngine/pull/154
A working custom build can be found here: https://filehorst.de/d/ewbBFvua

**Comment by Bloodbat** [comment]
> I created a PR here: #154 A working custom build can be found here: https://www.mediafire.com/file/6aqpzanvhz6pny6/TheForceEngine_midiPatched.zip/file

I tested your build, thanks, it works as expected: MIDI outputs through the proper synth. Adding it to the GUI would also be great :)

**Comment by Kirtai** [comment]
It would be nice to have hardware MIDI out too for people with hardware synths.

**Comment by Bloodbat** [comment]
I tested the current release. Thanks for adding this; but the feature is buggy: the option can be set by editing the midiDevice in settings.ini and it works properly; however when trying to set it using the GUI only the first MIDI device (0) is listed. I tested this under Windows (device 0 is the MS synth, in effect leaving it as it was before this feature request); when a different device is set by hand in settings.ini the GUI ignores it whenever it is opened and resets it back to device 0 with no possibility to change it from there.

**Comment by luciusDXL** [comment]
This is still open because of this issue. It seems to work well for audio devices but not midi, which is still something that needs to be looked at.

**Comment by luciusDXL** [comment]
Implemented in version 1.08

**Comment by Bloodbat** [comment]
Thanks :)
