### ISSUE TITLE
Engine crashes with no game data selected

### ISSUE THREAD

**Issue by coelckers** [luciusDXL/TheForceEngine#152]
I still own an old CD of this game, so no settings for GOG or Steam paths exist.
So I did the usual thing I do for source ports of old games and put the engine into the same folder as my game installation.

This, however, did not start the game but caused a crash. 
I had to set up the game path manually to make it work.

At the very least this should output a message what to do, but ideally should start the game from the current folder, as virtually every other source port for a 1990's game is doing.

**Comment by SirYodaJedi** [comment]
I don't think it's a good idea to have the game data directly in the exe directory, as this would cause inter-game contamination once Outlaws support comes around. I think the better approach would be to have a `./games/DARK/` directory that is read from automatically (when running game `DARK`), with a readme in it that explains that TFE will load the contents of that directory before looking in the source data path.

**Comment by luciusDXL** [comment]
The crash isn't supposed to happen, it should show a message. So that is a regression that occurred and needs to be fixed. As for autodetecting from the same directory, that would be useful. Thanks for the feedback.

**Comment by luciusDXL** [comment]
Fixed in version 1.01.
