### ISSUE TITLE
[Bug Report] Dark Forces - PDA Map viewer input problems when moused over clickable arrows

### ISSUE THREAD

**Issue by Abbanon** [luciusDXL/TheForceEngine#156]
Experienced in release v1.0

When you have the mouse pointer over any of the clickable PDA Map navigation arrows (pictured), pressing any keyboard inputs bound to map navigation will instead activate the movement arrow that you're currently moused over.
![Screenshot_2](https://user-images.githubusercontent.com/37251822/208894405-e2ea341b-8ec0-4383-b9f6-554fc053872e.png)

**Comment by TP555** [comment]
Hi

Do you mean the Highlighted Cursor when Click  ?

**Comment by TP555** [comment]
@Abbanon

ok , yes can reproduce this so !
Affects both Software and OpenGL  !

**Comment by luciusDXL** [comment]
How interesting, thanks for the report.

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
