### ISSUE TITLE
Translate UI for Ukraine

### ISSUE THREAD

**Issue by kirill0ermakov** [luciusDXL/TheForceEngine#157]
Hello! Maybe I can help to growth project and translate UI for English to Ukraine.

**Comment by luciusDXL** [comment]
There is some work needed to better support localization, such as full UTF-8 system in the System UI. However, once that happens, translation to Ukraine sounds like a great idea.

**Comment by luciusDXL** [comment]
I'm going to close for now - once we have better support for this kind of thing, then projects like this can move forward.
