### ISSUE TITLE
Crash Switching Audio Device, Exiting

### ISSUE THREAD

**Issue by paulrrogers** [luciusDXL/TheForceEngine#160]
When switching audio device on Windows 10, TFE won't play sounds on the new device, only music. Also, after switching twice in one session I got this crash during the second mission: SEH Exception. Having trouble reproducing it, and I had been switching to OBS and other apps while getting recording setup. So it's possible the audio switch issue is unrelated or just part of the problem.
[crashdump.zip](https://github.com/luciusDXL/TheForceEngine/files/10283311/crashdump.zip)

Here's another crashdump, this time when I was exiting the game, going back to 'DOS':
[crashdump2.zip](https://github.com/luciusDXL/TheForceEngine/files/10283384/crashdump2.zip)

Yet another crash, this time on exit, hadn't changed audio devices though was switching away and back to game a few times:
[crashdump3.zip](https://github.com/luciusDXL/TheForceEngine/files/10283454/crashdump3.zip)

**Comment by luciusDXL** [comment]
The final crash was in the OpenGL graphics driver, so unfortunately I don't have any way of debugging it. 
As for the others, TFE doesn't handle switching audio devices gracefully while running - so your best bet is to setup your sound before starting TFE.

**Comment by TP555** [comment]
Hi

@ paulrrogers

I think no App or Game , will like that , when you Switch the Audio , during running it   !

**Comment by luciusDXL** [comment]
I'm going to close this for now. Changing the audio setup while the application is running is not likely to ever work. The driver crash was unfortunate, but I have no way of debugging it.

If you continue to have crashes due to driver issues, please open a new bug detailing that and I can attempt to look into it further.
