### ISSUE TITLE
[bug report] Thermal Detonators do double damage when compared to Vanilla

### ISSUE THREAD

**Issue by VexFidel** [luciusDXL/TheForceEngine#163]
This isn't really a bug, but a variation in behaviour when compared to Vanilla DF. Thermal detonators in Vanilla DF do reduced damage to players compared to enemies, likely to reduce the danger of splash damage to the player. While the damage from a single direct detonator hit is enough to kill a Gran or Trandoshan (which I believe have 45 hit points) in either engine, the player takes 22-23 hit points of damage from a direct hit in Vanilla, whether from their own detonators or an opponent's. This behaviour has not been replicated in TFE as of yet.

I have included a small test .gob to demonstrate the damage difference. Firing a thermal detonator directly at the wall (without moving or adjusting the player's angle at all) deals 29-30 points of splash damage to the player in TFE, and only 15 points of splash damage in vanilla.  Walking up to the wall and firing deals 44-45 points of damage in TFE, and 22 to 23 points of damage in vanilla.

In Vanilla:
![DetTestVanilla](https://user-images.githubusercontent.com/81818997/209293844-93b18a75-1aaa-46dc-b465-5f9f954baff7.png)
In TFE:
![DetTestTFE](https://user-images.githubusercontent.com/81818997/209293857-eb53ef96-7525-4540-9791-15778735b1f6.png)
Testing GOB:
[DETTEST.zip](https://github.com/luciusDXL/TheForceEngine/files/10293320/DETTEST.zip)

**Comment by luciusDXL** [comment]
Thanks for the report.

**Comment by Q3BFG10K** [comment]
I'm playing this for the first time and was getting ripped a new one on Jabba's ship. The extra thermal detonator damage against me explains a lot of deaths.

**Comment by luciusDXL** [comment]
Fixed in version 1.01.
