### ISSUE TITLE
Player does not "climb" 2nd altitudes properly while jumping

### ISSUE THREAD

**Issue by VexFidel** [luciusDXL/TheForceEngine#165]
Another vanilla-compatibility issue, this time regarding 2nd altitudes. Noticed that if the player travels to this point in Assassination on Nar Shaddaa, and then tries to jump onto the catwalks surrounding it, the player will always fail the jump in TFE 1.01 and earlier:

![image_2022-12-24_200151339](https://user-images.githubusercontent.com/81818997/209428675-43bc5bd7-8723-4232-8ea7-f9aed6adb25e.png)

It appears that the player is unable to "climb" 2nd altitudes while jumping, meaning that they won't be able to overcome a 2nd altitude that is taller than their jump height. This is in contrast to Vanilla, where that jump should be achievable.

I've included another small test .gob that replicates the equivalent heights of the AoNS jump as well as some other 2nd altitude variations. As expected, the player is able to make the jump from the Y=2.0 squares to the Y=8.0 2nd altitude sector in vanilla, but is unable to clear the 2nd alt in TFE as of yet.

[2NDALT.zip](https://github.com/luciusDXL/TheForceEngine/files/10298265/2NDALT.zip)

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
