### ISSUE TITLE
[Rendering Bug] Gas Mask disappearing or when it appears ends up not being fullbright

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#167]
Version: 1.0
Game: Dark Forces
Renderer: GPU at 200p
Mod: Imperial Academy

As shown in the clip the gas mask disappears, yet is in use. Then when it does render it ends up being dimmed even in a lit room

https://youtube.com/clip/UgkxiqRla2t4NYk_7Uz_QCovzq5qCMBvdCfq?si=EnSIkaIECMiOmarE

**Comment by luciusDXL** [comment]
So this only happens in 320x200 mode - even 200p widescreen is fine.

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
