### ISSUE TITLE
PLANE shading in 3D objects being affected by planar scrolling when it shouldn't be

### ISSUE THREAD

**Issue by VexFidel** [luciusDXL/TheForceEngine#168]
![image_2022-12-25_185426506](https://user-images.githubusercontent.com/81818997/209460860-348b9422-d089-4160-a973-24842010d2ca.png)

So essentially, in Vanilla any object with PLANE shading (such as the various bridge/grating 3DOs) will be affected by the scroll floor/ceiling textures of the sector they're in, but only on the relevant side (so a bridge over a moving conveyor will have it topside scroll, but the underside will remain static)

At present (TFE 1.01) it looks like possibly both overside planes (floors) and underside planes (ceilings) will scroll if the sector in question has a scroll_floor command. I haven't checked it with scroll_ceiling yet, but will later for debugging purposes.

This bug can be observed in Bridge2.gob, a test gob I sent earlier in the project's development. When creating bridge2.gob, I swapped out the plane-shaded topside of the "fake" bridge with regular textured 3dos so that they wouldn't scroll with the river underneath, but left the underside of the bridge with plane shading. In TFE, the underside of the bridge (pictured above) will scroll along with the river, which does not occur in Vanilla

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
