### ISSUE TITLE
Version Closer To Center of Title Screen

### ISSUE THREAD

**Issue by paulrrogers** [luciusDXL/TheForceEngine#173]
Would be nice to see the version number  closer to the center of the TFE title screen. Since I play ultra-wide I actually only record the center 16:9, so the current version gets cut.

May help with diagnosing issues found watching video recordings, such as from Twitch or YouTube.

BTW: Love the logo with the subtle sheriff's star embedded within the imperial symbol.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
