### ISSUE TITLE
[Bug] Elevator does not rotate to it's next postion. Only raises

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#180]
Version: 1.01
Game: Dark Forces
Mod: Secbase Revisited

In TFE the elevator leading back to the start of the mission does not rotate when raising again to the highest point.

![Screenshot 2023-01-07 13-40-40](https://user-images.githubusercontent.com/19301383/211166314-229e0acd-e53a-423a-9e7b-73fecf9ca168.png)
The elevator in question

![Screenshot 2023-01-07 13-41-49](https://user-images.githubusercontent.com/19301383/211166317-ecdb30c9-0227-4e28-802e-69ad335e7288.png)
Where it ends up

![Screenshot 2023-01-07 13-41-52](https://user-images.githubusercontent.com/19301383/211166321-601c7736-6e9c-4abb-8878-bf45898a3d3b.png)
Where it should be pointing

https://youtube.com/watch?v=xt-5tzg9kNU&si=EnSIkaIECMiOmarE&t=889

Timestamp of the elevator in DOS

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
