### ISSUE TITLE
[Bug] Autoaim priority for explosive barrels

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#181]
Version: 1.01
Game: Dark Forces
Mission: Fuel Station, but could be any level with enemies near explosive barrels

TFE seems to hold a higher priority for explosive barrels over enemies. This doesn't seem to be the case in DOS. 

Also seems like scenery objects take autoaim priority. Tested on Coruscant - The Imperial Capital.

https://youtube.com/watch?v=qAs5DbfP_F0&si=EnSIkaIECMiOmarE&t=427

**Comment by luciusDXL** [comment]
Scenery objects have the "aim" flag cleared. So those objects must have had additional logics or really been explosives.

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
