### ISSUE TITLE
[Bug] Mission 1 of Don Sielke's Levels Tractor Beam switch doesn't open the last blast door

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#184]
Version: 1.01
Game: Dark Forces
Mission: Don Sielke's Dark Forces Levels Level 1

The tractor beam switch near where the save is only able to push an elevator to the done message and skips opening the last blast door needed to complete the level.

https://youtube.com/watch?v=t_t34UG3YqQ&si=EnSIkaIECMiOmarE&t=290 the tractor beam control area

[save007.zip](https://github.com/luciusDXL/TheForceEngine/files/10367807/save007.zip)

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
