### ISSUE TITLE
[Bug] Don Sielke's Mission 3 and 4 despawned assault cannon

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#186]
Version: 1.01.000-29-g29d2900e
Game: Dark Forces
Mission: Don Sielke's Levels Mission 3 and 4

The Assault Cannon on these platforms do not spawn. as shown in the screenshots

![Screenshot 2023-01-08 20-08-29](https://user-images.githubusercontent.com/19301383/211228163-fdebc3bf-8da1-4783-8c13-702fb1f14d47.png)

![Screenshot 2023-01-08 20-09-24](https://user-images.githubusercontent.com/19301383/211228171-95f92d24-daa4-47ae-b394-faf7e6334ed0.png)

the two above is DOS behavior

![Screenshot 2023-01-08 20-11-37](https://user-images.githubusercontent.com/19301383/211228183-e0ab0326-b33c-4e77-b9c1-b02535fbb259.png)

![Screenshot 2023-01-08 20-12-31](https://user-images.githubusercontent.com/19301383/211228195-43478180-4591-4704-a4b4-443061b3a2ef.png)

TFE

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
