### ISSUE TITLE
[Briefing Bug] Don Sielke's levels have their briefings skipped

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#187]
Version: 1.01.000-29-g29d2900e
Game: Dark Forces
Mission: Don Sielke's Levels for Dark Forces

When choosing a mission, after the game plays a cutscene before the briefing, TFE skips loading the briefings and goes straight to the level. This doesn't happen on DOS

**Comment by TP555** [comment]
Hi

can you may show that , i have Select a Mission , Cutscenes Plays , Quit Mission , Select a another one , Briefings was alltimes there  !

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
