### ISSUE TITLE
[Feature Request] Widescreen & Ultrawide for Cutscenes 

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#189]
Hi

Can you may expand the Screenspace for Cutscenes , even so far it the ScreenSpace allowed  ?

**Comment by luciusDXL** [comment]
The existing cutscenes cannot be made widescreen or ultrawide without stretching them. They are 2D art, so there is nothing to show beyond the borders. In the future, it might be possible to make custom widescreen cutscenes, but until then there isn't any practical way to achieve this.
