### ISSUE TITLE
Texture stretching, "Exterior Adjoin" Flag and No Wall Draw (Horizon) flag behaviour

### ISSUE THREAD

**Issue by VexFidel** [luciusDXL/TheForceEngine#190]
Making a blanket post for Exterior Adjoin issues because there's a few bits at play here. I've created a gob with examples of the issues that I know of - as far as I can tell all of these look "correct" in software, but incorrect in hardware. All screenshots use software rendering on the left and hardware rendering on the right.

MIDTEXTURES:
Adjoined walls with wall flag 1 1 (adjoining mid texture) inside a sector with Sector Flag 1 1 (sky) and 1 8 (exterior adjoin) set will "stretch" to fit the entire screen in vanilla and software. 

![image](https://user-images.githubusercontent.com/81818997/211713073-e83a25ce-9df7-47c7-8e08-d847d508126d.png)

A wall inside a sector with Flag 1 8 set but -without- the sky flag set, if it adjoins to a sky sector of lower ceiling height, will stretch to cover the entirety of their adjoin:

![image](https://user-images.githubusercontent.com/81818997/211713383-9f5aaed9-19af-4694-b49a-7150124dc5a8.png)

This can also be dynamically altered mid-game, by adjusting the height of the non-sky ceiling:

![image](https://user-images.githubusercontent.com/81818997/211713599-a206edfc-7258-43a2-a34d-d80529d49248.png)

HORIZONS & TOP/BOTTOM TEXTURES:
I think this one may have been resolved already, but sectors with the Horizon flag set will still draw their corresponding top/bottom textures in hardware, if adjoined to a sector without sky/pit flags. Technically this is a different issue, but there could easily be a relation between the issues.

![image](https://user-images.githubusercontent.com/81818997/211713917-ca3f441f-77b5-4ce0-a3cb-1578696fb3ab.png)

Sample gob:

[EXTADJ.zip](https://github.com/luciusDXL/TheForceEngine/files/10388759/EXTADJ.zip)

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
