### ISSUE TITLE
[Bug] Items get crushed and despawn from the game 

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#191]
Version: 1.01.000-40-g76c151e9
Game: Dark Forces
Level: Gromas Mines, and Stars End as examples
Items get crushed and despawn in TFE when they don't in DOS. 

![Screenshot 2023-01-11 20-40-37](https://user-images.githubusercontent.com/19301383/211957377-fa9edfa0-94c6-47b9-a373-16636c20e033.png)
The items in Gromas Mines (DOS)

![Screenshot 2023-01-11 20-45-00](https://user-images.githubusercontent.com/19301383/211957357-5990dfcd-148a-4022-b54a-f166d66b675a.png)
The items that should be in Stars End's secret (DOS)

![Screenshot 2023-01-11 20-51-03](https://user-images.githubusercontent.com/19301383/211957328-85ad71ca-cbfb-4435-9ed4-4bb30fe5f8ae.png)
TFE with coordinates

![Screenshot 2023-01-11 20-52-51](https://user-images.githubusercontent.com/19301383/211957256-137bbbcf-5d48-4ab2-ba3d-ac57eabd2783.png)
Stars End before

![Screenshot 2023-01-11 20-53-24](https://user-images.githubusercontent.com/19301383/211957281-9ef95ebd-8ab2-40c4-a27b-58dbb4bbe1f8.png)
Stars End after

**Comment by luciusDXL** [comment]
This is fixed locally, and will be fixed in the version 1.02 release.

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
