### ISSUE TITLE
Stars End Render Glitch with GPU Renderer

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#193]
Version: 1.01.000-44-g6359cd86
Game: Dark Forces
Mission: Stars End The Cloak

During the launch sequence near the end of the mission when the scene transfers from atmosphere to space there is a render glitch

![Screenshot 2023-01-14 00-01-07](https://user-images.githubusercontent.com/19301383/212456954-1d9483f7-d132-494a-a0d0-5547e0aff6f5.png)

![Screenshot 2023-01-14 00-01-17](https://user-images.githubusercontent.com/19301383/212456955-8a8f0edb-6d37-4b9c-bf97-f999af395cac.png)

Save provided near the cockpit. Just grab the ship log if it hasn't been obtained and press the switch

[save008.zip](https://github.com/luciusDXL/TheForceEngine/files/10416713/save008.zip)

**Comment by luciusDXL** [comment]
Fixed in the version 1.02 Release.
