### ISSUE TITLE
[Bug] Linux port, crash in Dark Tide 2

### ISSUE THREAD

**Issue by spacekomet** [luciusDXL/TheForceEngine#203]
Hello

I'm experiencing crash in mod Dark Tide 2, after I pick the scuba dive and swim in the water. 

Mod is downloaded from DF-21, https://df-21.net/downloads/levels/dtide2/dtide2_modern.zip

Here is compressed save. Unzip it and put it in the save folder. 
[save007.tfe.zip](https://github.com/luciusDXL/TheForceEngine/files/10475604/save007.tfe.zip)
After it's loaded, turn right and swim up to the furthest wall, and then turn around. 

Here is the log (however the error was not saved):
[the_force_engine_log.txt](https://github.com/luciusDXL/TheForceEngine/files/10475610/the_force_engine_log.txt)

Here is the actual error shown in the console:
```
tfelnx: /home/user/ForceEngine/TheForceEngine-audio/TheForceEngine/TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp:687: void TFE_Jedi::model_add(void*, JediModel*, Vec3f, fixed16_16*, f32, Vec2f, Vec2f, u32): Assertion `0' failed.
zsh: IOT instruction (core dumped)  ./tfelnx
```

Using linux port https://github.com/mlauss2/TheForceEngine/tree/linux3-audio-next

Anyone else with the same problem?

**Comment by mlauss2** [comment]
This seems to fix it, although I'm not sure whether this is the correct thing to do.

```diff
diff --git a/TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp b/TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp
index 1d32786a..a96805f1 100644
--- a/TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp
+++ b/TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp
@@ -46,7 +46,7 @@ namespace TFE_Jedi
        enum Constants
        {
                MGPU_MAX_MODELS = 1024,
-               MGPU_MAX_3DO_PER_PASS = 512,
+               MGPU_MAX_3DO_PER_PASS = 768,
        };
 
        struct ModelVertex

```

**Comment by spacekomet** [comment]
I tried with linxu4-audio-next (where I saw you merged the gpu limits changes into), and no problems anymore. Was able to successfully finish the level.
