### ISSUE TITLE
[linux] update the minimum requeriments adding the needed libraries for building it.

### ISSUE THREAD

**Issue by BielBdeLuna** [luciusDXL/TheForceEngine#208]
what  are the "IL" and "ILU" libraries?

**Comment by BielBdeLuna** [comment]
ok those are DevIL related libraries: libdevil-dev

**Comment by mlauss2** [comment]
I'll add something to the README file.  Thanks for the reminder.

**Comment by BielBdeLuna** [comment]
what command has to be added when launching the engine for the music? can the music be integrated in the engine already?

**Comment by mlauss2** [comment]
> what command has to be added when launching the engine for the music? can the music be integrated in the engine already?

Read the readme, at the bottom there's suggestions wrt. midi synthesizer and how to launch them.

**Comment by BielBdeLuna** [comment]
of course I did, but that explanation doesn't make clear how to do it. i have to add it after calling the engine?

**Comment by BielBdeLuna** [comment]
I get this message:

```
$ fluidsynth -s -L2 /usr/share/sounds/sf2/default-GM.sf2 
FluidSynth runtime version 2.2.8
Copyright (C) 2000-2022 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: error: Failed to bind server socket: 98
Failed to create the server.
Continuing without it.
fluidsynth: warning: Failed to set thread to high priority
Type 'help' for help topics.

> fluidsynth: warning: Failed to set thread to high priority
quit
cheers!
```

and then when I start the engine with `$ ./tfelnx `

I get the follwing regarding sound and music:

```
(...)
[Startup] TFE_AudioSystem::init
[Audio] Attempting to initialize Audio System using API 'Linux ALSA'.
[Audio] Default Audio Output ID: 0.
[Audio] Device Count: 11.
[Audio] Device: 'default', ID: 0, Output Channel Count: 32.
[Audio] Device: 'hw:HDA NVidia,3', ID: 1, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,7', ID: 2, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,8', ID: 3, Output Channel Count: 2.
[Audio] Device: 'hw:HDA NVidia,9', ID: 4, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,10', ID: 5, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,11', ID: 6, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,12', ID: 7, Output Channel Count: 8.

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

[Audio] Device: 'hw:HD-Audio Generic,0', ID: 8, Output Channel Count: 0.
[Audio] Device: 'hw:HD-Audio Generic,1', ID: 9, Output Channel Count: 2.
[Audio] Device: 'hw:HD-Audio Generic,2', ID: 10, Output Channel Count: 0.
[Audio] Audio initialized using API 'Linux ALSA'.
[Audio] Starting up audio stream for device 'default', id 0.

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

[Startup] TFE_MidiPlayer::init
(...)
```

now sound works but there isn't any music

any idea how to solve it?

**Comment by mlauss2** [comment]
Launch fluidsynth before you start tfe in another shell.

the log seems fine, fluidsynth is running.

List available midi synths:
```
$ aplaymidi -l
 Port    Client name                      Port name
128:0    FLUID Synth (79916)              Synth input port (79916:0)
```
then play a midi file to it:
```$ aplaymidi -p 128 01_-_Dark_Forces_Opening_Titles.mid```

If this works, then tfe works as well.

From another linux thread here I remember things that might help:
* You may need to remove the "snd_seq_dummy" kernel module,
* or make sure you have snd_seq support in your kernel,
* really, bother your distro about state of midi support,
* start fluidsynth with additional parameter "-m alsa_seq"
* All of these things are distro problems, not TFE problems.

**Comment by BielBdeLuna** [comment]
ok fluidsynth do work:
> I start the fluidsynth server as per your instructions with: **fluidsynth -s -L2 /usr/share/sounds/sf2/default-GM.sf2**

<details><summary>Toggle FluidSyth verbosity</summary>
<p>

```
$ fluidsynth -s -L2 /usr/share/sounds/sf2/default-GM.sf2
FluidSynth runtime version 2.2.8
Copyright (C) 2000-2022 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: warning: Failed to set thread to high priority
Type 'help' for help topics.

> fluidsynth: warning: Failed to set thread to high priority
```

</p></details>

> I don't close it

> I check it works with **aplaymidi -l**
```
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
128:0    FLUID Synth (16384)              Synth input port (16384:0)
```
so FluidSynth is in port 0 of client 128

> I check that aplaymidi actually plays a midi file in that port in specific with **aplaymidi -p 128:0 ./HL2--CP_Violation.mid**

> ahhhh... sweet Half Life 2 midi music comes into my ears :)

now the issue:

> start **$ ./tfelnx**

<details><summary>Toggle engine verbosity</summary>
<p>

```
(...)
[Startup] TFE_AudioSystem::init
[Audio] Attempting to initialize Audio System using API 'Linux ALSA'.
[Audio] Default Audio Output ID: 0.
[Audio] Device Count: 5.
[Audio] Device: 'default', ID: 0, Output Channel Count: 32.
[Audio] Device: 'hw:HD-Audio Generic,3', ID: 1, Output Channel Count: 8.

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

[Audio] Device: 'hw:DigiHug USB Audio,0', ID: 2, Output Channel Count: 0.

RtApiAlsa::getDeviceInfo: snd_pcm_hw_params error for device (hw:1,1), Invalid argument.

[Audio] Device: '', ID: 3, Output Channel Count: 0.
[Audio] Device: 'hw:HD-Audio Generic,0', ID: 4, Output Channel Count: 2.
[Audio] Audio initialized using API 'Linux ALSA'.
[Audio] Starting up audio stream for device 'default', id 0.

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.


RtApiAlsa::getDeviceInfo: snd_pcm_hw_params error for device (hw:1,1), Invalid argument.

[Startup] TFE_MidiPlayer::init
(...)
```

</p></details>

now it seems the engine doesn't read other clients/ports rather than the default "**Midi Through**"

here is a capture within the engine:

![midi clients and ports](https://user-images.githubusercontent.com/2709433/216784606-5168a404-9e92-41f3-8fd3-8bdc7a412c08.png)

so `the engine has some troubles with midi clients and ports`

**Comment by mlauss2** [comment]
The current master branch doesn't list all available midi devices, I'll look into that, because I see no reason why it should do that.

You can now either 
* remove the "snd-seq-dummy" kernel module (```rmmod snd-seq-dummy``` as root) to get rid of the "Midi Through" device
* or try my [audio-next](https://github.com/mlauss2/TheForceEngine/tree/audio-next) branch which lets choose from more midi devices.

**Comment by mlauss2** [comment]
I've opened #222 which should fix your selection box problem.  I don't usually test master, so I didn't notice until now, sorry about that.

**Comment by BielBdeLuna** [comment]
ok! :+1:

**Comment by mlauss2** [comment]
Try latest master branch, it now has the necessary code to select other midi devices.
