### ISSUE TITLE
Quit to DOS confirmation dialogs in German version has different colors

### ISSUE THREAD

**Issue by RC2225** [luciusDXL/TheForceEngine#211]
When clicking Programm beenden (Quit to DOS) the text is rendered pink with some red "ghosting".
I switched for fun to the Spanish version, where it happens partially in the Abort mission confirmation dialog. 
Tested on Linux and Windows.
![Pink text](https://user-images.githubusercontent.com/5329274/216111314-46be94d0-419f-4882-80d3-03cc7b94a785.png)

**Comment by TP555** [comment]
Hi

Yes , this Bug exists now since a long time  !
https://the-force-engine.freeforums.net/thread/126/lack-confirmation-prompts

**Comment by mlauss2** [comment]
Is this little dialog box a BM texture? Do you happen to know its filename?

**Comment by TP555** [comment]
Hi

@mlauss2 

no BM File , this kind of Menus Agent Menu also ! are a Anim File/s , was packed in "MENU.LFD"

[yesno.zip](https://github.com/luciusDXL/TheForceEngine/files/10572400/yesno.zip)

**Comment by mlauss2** [comment]
A palette issue maybe? I don't know how the ANIM format works, could you check whether the colors of the text "Programm Beenden" of the english version and the german version use the same values or different ones?

**Comment by TP555** [comment]
@mlauss2

[yesno ENG.zip](https://github.com/luciusDXL/TheForceEngine/files/10573421/yesno.ENG.zip)

**Comment by mlauss2** [comment]
it looks like TFE applies the palette "SECBASE.PAL" to the escape menu, instead of e.g. agentmnu.PLTT or menu.PLTT

**Comment by mlauss2** [comment]
With the menu.pltt palette applied to the escapeMenu, it looks like this now:
![image](https://user-images.githubusercontent.com/123231678/216553903-30c3c51e-c48c-471c-81fa-5901a3672caf.png)

The pltt files are identical in english and german versions, its just the DELT files that differ (obviously).  I have no idea what's wrong here.

**Comment by mlauss2** [comment]
I fixed it, see #216 
It's a bit hacky, but it gets the job done.  The code could be cleaned up a bit more.

**Comment by luciusDXL** [comment]
This has been fixed in the master branch.

**Comment by TP555** [comment]
Hi

Fixed now in 1.08
