### ISSUE TITLE
Dark Tide IV, Mission 1 hits assertion on level load

### ISSUE THREAD

**Issue by mlauss2** [luciusDXL/TheForceEngine#221]
Dark Tide IV, Mission 1: (dtide4_modern2.zip)
```TheForceEngine/TFE_Jedi/InfSystem/infSystem.cpp:2050: bool TFE_Jedi::inf_parseElevatorCommand(s32, KEYWORD, Allocator*, bool, InfElevator*&, s32&, InfLink*&): Assertion `sector0 && wallIndex0 >= 0 && wallIndex0 < sector0->wallCount' failed.```

The comment above it says the assert()s were specifically added for this mod; but it seems to work just fine in DOS.  Is this is a bug in the map, or something missing in TFE?

**Comment by luciusDXL** [comment]
Neither. It is a bug in DT 4 that works anyway in both DOS and TFE. Basically, mods are full of bad data that Jedi just handles, and this is a case of that. I should probably just remove the assert.

**Comment by luciusDXL** [comment]
I removed the asserts, they are no longer needed (the code handles the issue already).
