### ISSUE TITLE
Linux compile instructions

### ISSUE THREAD

**Issue by LiamDawe** [luciusDXL/TheForceEngine#231]
Hi, since the release download is only made for Windows, can we get some proper compile / build instructions added if there's not going to be a pre-made Linux build? :+1: 

The new release says:

> Updated the README with Linux build and run instructions.

But it doesn't? It mentions the needed libs but no instructions on how to actually build and run it

**Comment by mlauss2** [comment]
it's a bog-standard cmake project:
```
mkdir tfe-build
cd tfe-build
cmake -S /path/to/tfe/source/root
make
sudo make install
```
run with 
```
tfelnx
```

**Comment by LiamDawe** [comment]
Not everyone knows or remembers how to do it every time. Simply including the clear instructions are always helpful.

**Comment by mlauss2** [comment]
Sigh. I'll add some basic build instructions. Or a shell script which does what I wrote above...

**Comment by LiamDawe** [comment]
Why the "sigh"? Seems pretty _unnecessary_ when it's really quite a simple request to have basic instructions included.

**Comment by LiamDawe** [comment]
And again...

> Add step-by-step instructions on how to build and instal TFE Linux from source. (sigh)

This is really _unnecessary_ and pretty off-putting to give such an attitude for super simple requests.

**Comment by mlauss2** [comment]
I remember a time when linux users just knew what needed to be done. Granted that was before ubuntu existed.  Yeah I'm cranky about that.
But.. did the instructions work for you?  I basically copied my default workflow.

**Comment by wof8317** [comment]
The vast majority of FOSS projects have build instructions for those who want to build the project themselves, even on Windows. It helps us spend less time figuring it out for ourselves and more time using it. By not providing one, you are making yourself look less user-friendly than other projects.

**Comment by LiamDawe** [comment]
> I remember a time when linux users just knew what needed to be done. Granted that was before ubuntu existed. Yeah I'm cranky about that.

Okay...but you don't help people learn by not providing the info, and then giving a slightly off attitude when an honest request is made. I hope that makes sense.

> But.. did the instructions work for you? I basically copied my default workflow.

Will test when I get my next chance.

**Comment by mlauss2** [comment]
I think the "standard" Linux user nowadays wants a distro package.  Please ask your favorite distro about packaging TFE for you (if you want a Gentoo ebuild, ping me, I have one). This also eliminates a lot of unnecessarily filed issues when people try to build from source and don't have all prerequisites installed, ....
Let the distro package it for you!
That's also why there were no build instructions in the first place.  Distro packagers know what they are doing.

**Comment by RedCyberPandaz** [comment]
> I think the "standard" Linux user nowadays wants a distro package. Please ask your favorite distro about packaging TFE for you (if you want a Gentoo ebuild, ping me, I have one). This also eliminates a lot of unnecessarily filed issues when people try to build from source and don't have all prerequisites installed, .... Let the distro package it for you! That's also why there were no build instructions in the first place. Distro packagers know what they are doing.

I'm just gonna put this out here. You are making this needlessly difficult for linux users. Windows gets a nice little exe file while linux users are told to "Figure it out". And thats simply unfair. I'm an old school linux user, debian 3 woody was my first distro I installed when I was 8. I know my way around a terminal and the commands that I need to use and know how to do the more technical aspects of things I need to do when things break. As a developer, the least you could do is put proper prerequisites and build instructions for linux. I'll do it for you if you don't want to do it that bad. But writing the commands for the "standard" linux user to copy paste is bare minimum for linux support for software nowadays. It is not MY duty as a user to figure out which prerequisites I need and how I need to attempt to build and compile your software to get it to work, when microsoft users simple double click a file. Its unfair to the linux community. Not everyone wants to spend hours in the terminal trying to figure out why it keeps breaking.

**Comment by heidiwenger** [comment]
"You are making this needlessly difficult for linux users. Windows gets a nice little exe file while linux users are told to "Figure it out". And thats simply unfair."

Yes! Exactly this! When i downloaded the package and saw a few .dll files and a .exe i honestly had NO IDEA how to proceed nor what to do to make the thing run. Even though i'm a pretty seasoned Linux user. I was even thinking: huh, do i run the .exe just with Wine? My oh my.

**Comment by classilla** [comment]
It should at least list the prerequisites. Waiting for the distros to catch up is never a good strategy. There are lots of packages distros don't provide.

**Comment by TheEvilSkeleton** [comment]
>  Let the distro package it for you!
> That's also why there were no build instructions in the first place. Distro packagers know what they are doing.

As a packager, I appreciate it when build instructions are clearly written and discoverable.

**Comment by BielBdeLuna** [comment]
also there is a need to explain how to play the music as it's not straight forward opening the engine...

**Comment by sparr** [comment]
> I remember a time when linux users just knew what needed to be done

Speaking as a full time Linux desktop/laptop user for the last 15 years... There never was such a time. The only build system I've memorized the steps for is `aclocal && automake && autoconf && ./configure && make`. If you're using scons, cmake, qmake, ninja, maven, gradle, bazel, or anything else weird and/or new, I'm going to have to google, and that's going to be even more annoying if you didn't even tell me which one so I'm forced to look at the filenames and guess which build system they go with.

**Comment by mlauss2** [comment]
My apologies.

Now, let's turn this around: instead of complaining about what is missing, please help improve the documentation for other linux users.  I made the initial documentation based on what I thought other users might need, which is clearly lacking.
