### ISSUE TITLE
1.08 has now Linux version? Yet only TheForceEngine.exe in folder and readme is 1.02 (so not updated). How to run?

### ISSUE THREAD

**Issue by heidiwenger** [luciusDXL/TheForceEngine#232]
So in the extracted folder amongst Fonts Mods Shaders UI_Images UI_Text and Documentation sub folder there are only dll files and that TheForceEngine.exe.

How do i use this? There are no instructions and indeed that readme was not updated though the release notes indicated so?

**Comment by mlauss2** [comment]
you need to build it from source.
```
mkdir tfe-build
cd tfe-build
cmake -S /path/to/tfe/source/root
make
sudo make install
tfelnx
```

**Comment by LiamDawe** [comment]
Mentioned here https://github.com/luciusDXL/TheForceEngine/issues/231

**Comment by luciusDXL** [comment]
The instructions should be up to date.
