### ISSUE TITLE
[linux + Midi] - [feature request] - auto open the midi "server" on engine start and autoclose on exit, or even restart the "midi" server amidst the gameplay

### ISSUE THREAD

**Issue by BielBdeLuna** [luciusDXL/TheForceEngine#234]
as it is right now you need to open a secondary terminal and manually open the Midi "server" and then open the engine, and at the end exit the Midi "server" manually again.

now in GZdoom or Eduke32 this all happens transparet to the user, now in the case of GZDoom, it uses ZMusic a library separated from the engine that handles many MIDI servers that can be engaged from within the engine. could TFE adapt it's MIDI playing capabilities with a system like that?

**Comment by mlauss2** [comment]
I'm considering adding code to autospawn timidity or fluidsynth at lauch. I'm going to take a look at using fluidsynth as library dependency.  This would also work on Windows, with custom soundfonts...
No promises though.

**Comment by luciusDXL** [comment]
I am already working on integrated midi synth for version 1.10. I only released an earlier build so people can start using the Linux build and to get other fixes (like some AI and crash fixes).

**Comment by BielBdeLuna** [comment]
maybe an interesting selection could be the soundfont files?

**Comment by luciusDXL** [comment]
I have updated the README regarding the plan for internal midi-synthesis for version 1.10, so this issue is not needed anymore. TFE also will include a selection of sound fonts that can be used, so there will be a default without any setup required. So I'm going to close this feature request since I am not planning on automatically dealing with external midi servers.

**Comment by mlauss2** [comment]
As a workaround until Lucius' built-in fluidsynth is ready, you can also run fluidsynth as a normal system daemon:

* Edit the /etc/fluidsynth.conf to select your favorite soundfont
* systemctl enable fluidsynth.service
* systemctl start fluidsynth.service  (need to do this once).
