### ISSUE TITLE
[Feature Request] OpenGL 2.1 support for Raspberry Pi 3/4/400

### ISSUE THREAD

**Issue by JoshuaPettus** [luciusDXL/TheForceEngine#243]
I read in your information that supporting older versions of OpenGl would be a total stretch goal, so no worries.  I'm sure it would be a pain and half to implement.  But just wanted let you know there was at least one person who would be interested in trying to run it on an raspberry pi 400. :)   I did actually get it to compile.  I had to compile rtaudio and rtmidi myself as the current PiOS 64bit doesn't have the newest versions.  The version of devIL on the main repo was fine.  But then I hit the OpenGL limit when attempting to execute and saw I should have looked closer at the readme.

**Comment by jrugia** [comment]
Have you tried to run the game using the Zink driver? I don't know how far the support is on the Rpi but hopefully it exposes OpenGL 3.3+

**Comment by JoshuaPettus** [comment]
That's certainly an idea.  But I don't see any guides on how to install it on raspberry pi.  Only a few articles on experiments done with V3DV a few years ago.  Honesty it all seems a little too experimental for my purposes

**Comment by luciusDXL** [comment]
The GPU Renderer cannot work under OpenGL 2.1. So the only option is the software renderer, but there is already a feature request to avoid the OpenGL requirement when using it.

**Comment by jrugia** [comment]
@JoshuaPettus  First thing I'd try is to check if Zink is available in the software repo (or maybe it's already installed).  If neither is available you could try to compile Mesa yourself or find a pre-compiled one that features Zink. The run the game with "MESA_LOADER_DRIVER_OVERRIDE=zink %program%"

**Comment by JoshuaPettus** [comment]
@luciusDXL,  Ah Thank you!  That makes total sense and in that case I'll close this ticket
@jrugia Thank you! I gave it a shot with instructions to compile here https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/.

I worked my way through all the dependency issues to get through the configure stage, but unfortunately I get a crazy python3 error.  Perhaps it doesn't work with the version that ships with PiOS...

**Comment by jrugia** [comment]
> @luciusDXL, Ah Thank you! That makes total sense and in that case I'll close this ticket @jrugia Thank you! I gave it a shot with instructions to compile here https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/.
> 
> I worked my way through all the dependency issues to get through the configure stage, but unfortunately I get a crazy python3 error. Perhaps it doesn't work with the version that ships with PiOS... I'll try to figure it out later...

If you want you can add me on discord maybe I can help with the python error. My username is LinuxGamer#4817

**Comment by fac3l3ss79** [comment]
With some minor glitch with the mouse cursor (while pausing), but the game runs just fine on Raspberry OS 64 bit on opengl with the following command:

MESA_LOADER_DRIVER_OVERRIDE=zink MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 ./theforceengine

**Comment by JoshuaPettus** [comment]
So you managed to compile the zink driver?

**Comment by fac3l3ss79** [comment]
I didn't have to compile mesa or zink. As far as I know zink is already part of mesa. glxinfo says I'm using Mesa 20.3.5.
I did compile the engine, of course, and librtmidi and librtaudio, since you need newer versions than those provided by the official repo for the engine.
Zink as a big hit in the fps, but the game is definitely playable, at least on 600p or lower resolutions, with overclocking. There are no problems with the color palettes on opengl over zink, everything seems just fine, but these problems still persist in the cutscenes though and, in sotware mode, in some levels. 

Also, while compiling the engine on the pi 4/400 make sure to use clang: "export CC=clang" then "export CXX=clang++" before hitting "make".

**Comment by JoshuaPettus** [comment]
Yup that was my exact compile experience on RPi4 too.   Funny, I don't think I needed the -pthread on my x86 Fedora box.

That's great to know about zink!  I had no idea.  I'll definitely give it a try

**Comment by JoshuaPettus** [comment]
I can confirm it works great at 600p!  Thank you @fac3l3ss79!

Ive noticed it's slow at first but takes a min before it runs at what I would call an acceptable level.  But this is not the only game to do that.  It's a bit of a trend.  I wonder why?

On my RPI400 I have mine overclocked quite a bit but it's still stable and thermals very well

`force_turbo=1
over_voltage=8
arm_freq=2200
gpu_freq=750
[all]
gpu_mem=256` 

Also I setup ZRAM which effectively manages the limited 4Gigs (minus the 256mb given to the GPU) in a much better fashion when it goes over than dump it onto the sdcard.  I'll have to play with it a bunch more, when I can, to see if I'm indeed getting the most out of it.  But all in all I'm impressed with what it can do.

**Comment by fac3l3ss79** [comment]
@JoshuaPettus  I think you can safely set gpu_freq=800.
I'm using zram (installed with Pi Apps) and I'm getting around 20-30 fps for opengl, and around 60 for software at 600p on my rpi 400. So definitely playable

Also, openjkdf2 works with the same trickery, minus the need for zink. And with openjk/openjo, we can play all jedi knight games on the pi :)

Vulkan implementation in the force engine and get it working on the pi would be sick!

**Comment by fac3l3ss79** [comment]
@JoshuaPettus It seems that later builds give me worse performance. Don't know why. Try building from the source code available in releases and not from cloning through git

**Comment by JoshuaPettus** [comment]
That's interesting, I've only used the available releases.

**Comment by JoshuaPettus** [comment]
Just to add to anyone who read the thread and looking at it now.  As of the latest PiOS the zink driver " MESA_LOADER_DRIVER_OVERRIDE=zink" is no longer needed nor does it even work.  Which is good, it was an extra overhead.  JakeSmarter is correct MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 is still needed for some reason.

**Comment by fac3l3ss79** [comment]
With true color the colors display correctly ingame but not in cutscenes for me on pi OS bookworm. 
To correct all color problems you still need to use the zink driver with MESA_LOADER_DRIVER_OVERRIDE=zink

**Comment by JoshuaPettus** [comment]
Odd, i dont have those problems on bookworm. and the zink driver doesnt even work for me anymore
