### ISSUE TITLE
[Feature Request] Optionally no OpenGL dependencies at all

### ISSUE THREAD

**Issue by mlauss2** [luciusDXL/TheForceEngine#244]
As the title suggests: Gate off all GL-dependent code to be able to build a pure software-rendering-only binary of TFE.
Main motivation is my MIPS32 toys: They don't have FPU, and only dumb framebuffer. DF runs excellent in DosBox on them (despite the x86 to MIPS translation), but atrociously slow in TFE (at 800x480: <1fps with software GL 3.3 emulation for just ImGUI!).

I will try to get this to work.

**Comment by luciusDXL** [comment]
I am planning on improved low-end software renderer support using SDL to handle the window update from software. But this will be optional (even in software) - because proper OpenGL support enables improved performance at higher resolutions due to GPU-based palette to true-color conversion.
