### ISSUE TITLE
MIDIs Play incorrectly when using System MIDI or any option that isn't OPL or SF2

### ISSUE THREAD

**Issue by OpenRift412** [luciusDXL/TheForceEngine#248]
I don't know what you did last update but there are some really weird issues with the system MIDI/Midi Mapper option. Using my SC-55, there are instruments not playing, using the Microsoft GS Wavetable MIDI Synth causes tracks to play at the wrong volumes.

**Comment by luciusDXL** [comment]
Yes, there was a volume issue with the System Midi device. Can you try with the latest code in master and see if that improves it for you?
