### ISSUE TITLE
[Feature Request] Make officers or guards drop Bryar Pistol

### ISSUE THREAD

**Issue by eclenaeu** [luciusDXL/TheForceEngine#250]
I don't know if it has happened to you, during the progress of the vanilla campaign, when passing the level, changing the difficulty of the game and, for some reason, no longer having the Bryar pistol. All weapons can be acquired as the game progresses, except the Bryar pistol, this one, if you want it again, you need to do the stages before changing the difficulty, in that chosen difficulty and it is very annoying to redo stages, just to get a single weapon.

**Comment by luciusDXL** [comment]
That is definitely odd and might be a bug (though it might be a bug in the DOS game as well). As for the feature request, it seems like something that can break mods that use the Jabba level to take away the pistol and sometimes never give it back. It can be optional, of course, but might also be better as a mod. So I will have to think about it. :)

**Comment by paulrrogers** [comment]
Noticed this too, for me it was indeed during the Jabba level that I lost it and never seem to get it back. Would be nice to fix, even if as a mod or part of community patch.

**Comment by luciusDXL** [comment]
I'm going to close this as this feature will break mods.

**Comment by paulrrogers** [comment]
@luciusDXL FYI you can "close as unplanned" in GitHub with the arrow next to close. Then it's gray instead of purple
