### ISSUE TITLE
Regarding linux and installation

### ISSUE THREAD

**Issue by VonKossa** [luciusDXL/TheForceEngine#254]
Hi!
Is there some way to run TheForceEngine on linux without issuing "make install"?
As it seems for now the files must reside in /usr/local/bin, /usr/local/share/TheForceEngine/ or you can add another hardcoded path via parameters before building.
If think it would be neat to have the possibility to run TheForceEngine from one folder without having a hardcoded path.
Makes portability easier.

Thanks in advance

**Comment by VonKossa** [comment]
ok. Thanks, but then i am doing something wrong because if i execute ./theforceengine in the build directory i get:

[Main] The Force Engine 
v1.09.100

[Error : Main] Cannot load key names.

**Comment by mlauss2** [comment]
cmake sets up the build directory with symlinks to all the necessary support files.  Unless you deleted the source tree after building or did a "make clean" it should work.
Please show the output of "ls -la" of your build directory; and "ls -la UI_Text"

**Comment by VonKossa** [comment]
I have not deleted source tree or made a "make clean".
I have no UI_Text, at least not in my build directory, maybe in some of the subfolders....

ls -la
total 3372
drwxr-xr-x  4 user user    4096 Feb 20 19:22 .
drwxr-xr-x  5 user user    4096 Feb 20 19:19 ..
-rw-r--r--  1 user user   29327 Feb 20 19:19 CMakeCache.txt
drwxr-xr-x  6 user user    4096 Feb 20 19:22 CMakeFiles
-rw-r--r--  1 user user  359400 Feb 20 19:19 Makefile
drwxr-xr-x 21 user user    4096 Feb 20 19:19 TheForceEngine
-rw-r--r--  1 user user    4368 Feb 20 19:19 cmake_install.cmake
-rwxr-xr-x  1 user user 3033752 Feb 20 19:22 theforceengine

**Comment by VonKossa** [comment]
hmmm i think i know what i did wrong, i did not  specify a build type. Oups.... :(

**Comment by mlauss2** [comment]
Oh, where is your "ln" binary located?  I suppose it's NOT /usr/bin/ln ?  What distro do you use?

**Comment by mlauss2** [comment]
Try PR #255 please, I'm 99% certain it'll fix your particular problem (unless you don't have a "ln" binary: you are on your own with your strange symlink-hating distro).

**Comment by VonKossa** [comment]
I am using Gentoo.
ln is located in /bin/ln

**Comment by mlauss2** [comment]
> I am using Gentoo. ln is located in /bin/ln

I did the usr-merge a while back, but I remember that even Gentoo has a symlink /usr/bin/ln pointing to /bin/ln.  In any case, #255 will fix your problem as well.

**Comment by VonKossa** [comment]
Yes, now it works. Thank you very much. :)
