### ISSUE TITLE
The 'dead' sprint -- dead people shouldn't be able to change weapons like Kyle Katarn can!

### ISSUE THREAD

**Issue by BielBdeLuna** [luciusDXL/TheForceEngine#257]
Katarn is so badass that he can change weapons when dead! :)

**Comment by BielBdeLuna** [comment]
my proposal when the player is dead:
 - if the player presses, **next weapon**, or **prev weapon** or **any weapon button** go to revive the next life like if we hit **esc**

**Comment by luciusDXL** [comment]
This was fixed (certain types of input wasn't properly disabled).
