### ISSUE TITLE
The 'dead' sprint -- the best way to kill a bunch of enemies is to be dead they kill among themselves

### ISSUE THREAD

**Issue by BielBdeLuna** [luciusDXL/TheForceEngine#258]
enemies keep shooting at the player after he dies, now those shots when there are a bunch of enemies around can kill other enemies, and since there isn't any infighting this can cause to have a lot of corpses around the player without any reasonable reason. this alongside the lives system can be abused.

proposal: 
- make enemies only shot if there is a clear line of sight that wouldn't cause any other enemy get pain.
- make the enemies shot perfectly linear **-only when the player is dead-** so no bad shots can cause other enemies any pain.

**Comment by luciusDXL** [comment]
Fixed - the enemies should stop shooting a short time after the player dies.
