### ISSUE TITLE
Cannot find GOB files, plus engine hard freeze

### ISSUE THREAD

**Issue by gapf2010** [luciusDXL/TheForceEngine#259]
Using TFE version 1.09.100 on Windows 11 here, fully updated. PC is a laptop with a Ryzen 7 Pro 4750U CPU, 16GB RAM using the integrated GPU. I have the original DOS game, so I copied the whole DARK directory found on the CD (which contains the DARK.EXE file as well as DARK.GOB, SOUNDS.GOB, SPRITES.GOB and TEXTURES.GOB files) to the TFE directory. After this, I tried to configure the location of the game on TFE, but typing the directory on the "Game source data" page does nothing. The engine insists that the files are not there. If I click the "Browse" button to choose the directory, the PC freezes completely just after clicking the button and I have to reboot.

**Comment by TP555** [comment]
Hi

Try in your Force Engine Folder  with Games\Dark Forces , this will Automaticly find from TFE.
The Freeze sounds may a Windows or Hardware issue , almost Memory or something OC like XMP etc.   !

**Comment by gapf2010** [comment]
Is TFE case-sensitive regarding filenames?

**Comment by TP555** [comment]
Hi

Try to Rename all Gob , lfd Files , ex. DARK.GOB , SOUNDS.GOB , if fixed this your problem  !
TFE works without problems under Windows 11  !

**Comment by luciusDXL** [comment]
Windows does not use case-sensitive filenames. When you copied your data, did you include the LFD/ directory?

**Comment by luciusDXL** [comment]
I believe this should be resolved by copying all of the needed files (see above). So I'm going to close for now.
