### ISSUE TITLE
Version In "Settings -> About" Inaccurate?

### ISSUE THREAD

**Issue by paulrrogers** [luciusDXL/TheForceEngine#261]
On the Settings / Configuration "About" screen I see version 0.9.0 yet from the main menu it reads 1.9.1.

**Comment by TP555** [comment]
Hi

Can't confirm that  !

It shows in the Main Screen 1.09.100  !
About Screen is Empty  !

**Comment by paulrrogers** [comment]
Strange, on a different computer I also get an empty content area for Settings -> About.

**Comment by luciusDXL** [comment]
The _About_ tab needs to be properly updated.

**Comment by luciusDXL** [comment]
Fixed in version 1.09.200.
