### ISSUE TITLE
Blue Windows On Jabba's Ship

### ISSUE THREAD

**Issue by paulrrogers** [luciusDXL/TheForceEngine#262]
When I ran TFE v1.9.1 with community patch on my laptop I noticed some, not all, windows were solid blue. Removing the community patch doesn't seem to have helped, or switching to the classic renderer.

![df-tfe-jabbas-ship-blue-windows](https://user-images.githubusercontent.com/5749738/224594039-06d0cb3d-07db-4465-987d-97b1d552f66b.png)

[save001.zip](https://github.com/luciusDXL/TheForceEngine/files/10952968/save001.zip)

**Comment by DatMaxNub** [comment]
Not a bug. That's been in the game since 1995.

**Comment by paulrrogers** [comment]
Wait, so the blue windows are intentional?! If so that's ... ugly.
