### ISSUE TITLE
Dark Tide 3 - Cause 99% GPU Usage + Frame Drops with 2160p in-Game Res  !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#264]
Hi

In the Big Main Hall , the pass the follow Gate cause short lagging FPS with 2160p in-Game Upscale , 1080p works fine  !
High GPU Usage and also Higher CPU Usage  hmm  ?

![tfe_screenshot_Mon-Mar-13-14_05_33-2023_0](https://user-images.githubusercontent.com/46653671/224711286-297e2268-8228-4d6c-bda3-b16f421c8ffd.jpg)

![tfe_screenshot_Mon-Mar-13-14_05_33-2023_1](https://user-images.githubusercontent.com/46653671/224711313-3ef02e8b-c9d6-45c8-b65b-cbbc19cb6876.jpg)

TFE Tested Version 1.09.100
Dark Tide 3 : Modern Version with Bitcores Fix

**Comment by mlauss2** [comment]
Since you mentioned at 1080 there's no such framedrop, and the render commands submitted are the same regardless of display resolution, I suspect that this is related to gfx card and/or driver.
PS: Where'd you get the high-res stormtroopers from? They look very out-of-place compared to the player weapon and the ones they dropped :)

**Comment by luciusDXL** [comment]
This isn't a bug or issue, so I'm closing. There will be more optimization work done in the future for TFE.

**Comment by TP555** [comment]
> This isn't a bug or issue, so I'm closing. There will be more optimization work done in the future for TFE.

Hi

Yeah i think so the GTX950 is too less, but it was realy weird, because this was only on some Move/Looking Points, and not continuously, so i had more understand the GPU Limit.

> PS: Where'd you get the high-res stormtroopers from?

From Discord User Jerreth, was may from TFE or DF-21.
But i have also Tested without it, was the same issue.

Cheers!

**Comment by luciusDXL** [comment]
> > This isn't a bug or issue, so I'm closing. There will be more optimization work done in the future for TFE.
> 
> Hi
> 
> Yeah i think so the GTX950 is too less, but it was realy weird, because this was only on some Move/Looking Points, and not continuously, so i had more understand the GPU Limit.
> 
> > PS: Where'd you get the high-res stormtroopers from?
> 
> From Discord User Jerreth, was may from TFE or DF-21, and a very good Work before the Remaster Version! But i have also Tested without it, was the same issue.
> 
> Cheers!

The perf hit in that area is triggered by the extra overdraw due to the way the doors are drawn. This isn't really a specific issue though, it just points to the need for a general optimization pass, which is why I closed the issue.
