### ISSUE TITLE
[Feature Request] In-game Captions / Subtitles

### ISSUE THREAD

**Issue by paulrrogers** [luciusDXL/TheForceEngine#265]
It's hard to hear Kyle and Jan's talking in game with all the ambient, weapon, and enemy noises. Seems to get worse in latter missions. It would be nice to have in-game captions or sub-titles for all the mission voice overs, and even the enemy barks and grunts.

Alternatively, a way to adjust the voice audio level separate from other sound volume could help too.

**Comment by luciusDXL** [comment]
This has been added in version 1.09.4
