### ISSUE TITLE
[GPU Renderer] Textures rendering in the GPU Renderer but doesn't in Software/DOS

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#267]
Version: 1.09.100
Game: Dark Forces
Level: Free Kelly https://df-21.net/downloads/missions.php?viewid=1513935647

At the beginning of the level the GPU renderer is rendering textures that do not show in Software and DOS near the entrance to the fortress, as shown in the screenshots. 

GPU Renderer:
![Screenshot 2023-04-02 21-01-32](https://user-images.githubusercontent.com/19301383/229390364-464380f8-a08a-481f-8541-7fb2b86f0b8d.png)

Software: 
![Screenshot 2023-04-02 21-01-41](https://user-images.githubusercontent.com/19301383/229390378-130c03bf-eaf9-4aa4-86d5-8e72ccf3dec2.png)

**Comment by luciusDXL** [comment]
This has been fixed in master and will be fixed in the next release.

**Comment by luciusDXL** [comment]
Fixed in the 1.09.5 Release.
