### ISSUE TITLE
Unable to jumb while running (Dark Forces)

### ISSUE THREAD

**Issue by sedenion** [luciusDXL/TheForceEngine#269]
Unless "autorun" is enabled, it seem not possible to jump while running in "Dark Forces". This is critical for some missions where long jumps are required.

**Comment by luciusDXL** [comment]
I have never had problems jumping while running, I just tested again to be sure (both autorun enabled and disabled). Which version are you running? What keys do you have run and jump bound to?

**Comment by sedenion** [comment]
I use the 1.09.100 Windows x64. My Dark Forces version is french DOS version.

Keys mapping:
Run : LSHIFT - B
Jump : Space - A

**Comment by Slider-Whistle** [comment]
https://www.mechanical-keyboard.org/key-rollover-test/ Maybe your keyboard suffers from bad key rollover?

**Comment by luciusDXL** [comment]
Unfortunately, I don't have a French AZERTY keyboard - but I can say it works correctly on an English QWERTY keyboard. I would recommend trying a different keyboard or remapping the keys.

**Comment by sedenion** [comment]
I tested the keyboard on the given website, and indeed and surprisingly my keyboard do not correctly register this very specific combo Z (W) + LSHIFT + Space... After some googling I discovered I am not alone, it seem that it's a known "feature" of the Logitech K740.
