### ISSUE TITLE
200p doesn't appear to be working right

### ISSUE THREAD

**Issue by Slider-Whistle** [luciusDXL/TheForceEngine#271]
Black bars are inserted down the sides, video is visibly truncated. Switching to 240p gets rid of the black bars, but seeing as that's not the game's native resolution, the in-game video becomes visibly stretched instead.
200p:
![200-1](https://github.com/luciusDXL/TheForceEngine/assets/33862922/68910fd1-56f2-4966-8d68-46eb46b81cfa)
![200-2](https://github.com/luciusDXL/TheForceEngine/assets/33862922/312668ad-748d-4e77-b573-37ff6c5fea57)
240p:
![240-1](https://github.com/luciusDXL/TheForceEngine/assets/33862922/0633ef8c-a095-43cc-ba1f-a68013b27e41)
![240-2](https://github.com/luciusDXL/TheForceEngine/assets/33862922/58c91f12-458b-4c89-acb0-bcad502c110b)

If needed, I can send config files.

**Comment by luciusDXL** [comment]
200p will have black bars if you are using a widescreen monitor. It should be 4:3. If you check the Widescreen option, then you should get 200p but widescreen, which will fill the space.

**Comment by Slider-Whistle** [comment]
I'm using a CRT actually turned to the resolution 320*200. I didn't think to try ticking the "widescreen" option.
![Sun 28 May 01:28:57 UTC 2023](https://github.com/luciusDXL/TheForceEngine/assets/33862922/5602533d-c207-4fd0-b896-dadd4738a325)
Borders still appear in in-game menus, until a level is actually loaded.
![Sun 28 May 01:29:02 UTC 2023](https://github.com/luciusDXL/TheForceEngine/assets/33862922/652648e9-29c4-4587-8520-45849ca4ae16)
After that point, the game (and pause menu) do actually fill the screen.
![Sun 28 May 01:29:15 UTC 2023](https://github.com/luciusDXL/TheForceEngine/assets/33862922/006c1e17-a115-4b0d-8f16-9f262e2cd8ea)
However, (and I haven't seen the original game to compare), I still think the text at the top left still looks crushed.

**Comment by Slider-Whistle** [comment]
Forgot to mention, using Linux (didn't realise support was only recently added), and with resolution set to 400p so I can actually use the port's main menu before switching it down to 200p when in-game (the border issue happens either way, and apparently with either "Widescreen" setting apparently).

**Comment by luciusDXL** [comment]
Is your monitor using a "tall screen" resolution by chance (taller than 4:3, such as 1280x1024)? That might be broken again. the Widescreen option should only be needed if the monitor is wider than 4:3.

**Comment by Slider-Whistle** [comment]
640\*400 when starting the program up, and I switch it to 320\*200 once in-game, though I've tried leaving it at just 640\*400 the whole time as well

**Comment by luciusDXL** [comment]
No, I meant the native or desktop resolution. There was once a bug when the native resolution was taller than 4:3, I wonder if there is a regression.

**Comment by Slider-Whistle** [comment]
Oh, I see. Technically none, but 1024\*768@75hz is marked as the "preferred" resolution

**Comment by MarcoWanke** [comment]
Or maybe the explanation is just that simple? The art work in the mission briefing screens and cutscenes are designed in a 4:3 aspect ration by hand back in 1995. For everything grater then 4:3 you will get black bars. Its the same in old movies. Wrong aspect ration? You have to choose! Stretch it (this will look fat and squished) or letterbox it.

200p in 16:9
Mission briefing has black bars.
![Unbenannt](https://github.com/luciusDXL/TheForceEngine/assets/137448969/83c37130-8748-4200-9e95-f29742a483ef)

Ingame not
![theforceengine exe Screenshot 2023 09 06 - 16 38 44 33](https://github.com/luciusDXL/TheForceEngine/assets/137448969/a0828ac6-b529-4f75-b545-d9c7baf0eaee)

Thats some kind of normal behavior.

**Comment by Slider-Whistle** [comment]
@MarcoWanke Testing the game through QEMU, it seems like I must be wrong about a couple of assumptions I made about Dark Force's video. If my testing isn't wrong, it seems like the game uses 640\*400 globally, at least by default? Trying that with TheForceEngine however, I still get inappropriate black bars.

This is how the actual game looks, at least according to QEMU:
![brief](https://github.com/luciusDXL/TheForceEngine/assets/33862922/0fcc7465-a0d8-4e8b-8b09-b3486dbc902e)
![game](https://github.com/luciusDXL/TheForceEngine/assets/33862922/5b567175-7637-419b-8630-45eda5636648)

**Comment by Slider-Whistle** [comment]
Just for any possible interest, this is still reproductable with the latest git source on my setup.

I might be missing the intended way of playing the game in 320\*200. Normally I start the game up in 1440\*1080p (since this source port's main menu won't render any options when run at 320\*200), and then use xrandr to switch my resolution to 320\*200. Most game engines don't really know how to handle the GPU's video mode being switched mid-gameplay (though many can handle it gracefully), so maybe I'm missing some command line argument I'm meant to be using to skip the title screen?

**Comment by luciusDXL** [comment]
TFE uses a virtual frame buffer to handle different resolutions. Cutscenes and fullscreen UI is rendered into a 320x200 buffer and then upscaled. TFE assumes that the original game was rendered at 320x200 at 4:3 (the way I originally played it), which is why it uses the aspect ratio it does. Anyway, I don't plan on changing this anytime soon, so I'm going to close the issue.
