### ISSUE TITLE
GLEW fails to initialize if running with `SDL_VIDEODRIVER=wayland`

### ISSUE THREAD

**Issue by paricbat** [luciusDXL/TheForceEngine#275]
I'm using Fedora 38 with GNOME.
When I run `SDL_VIDEODRIVER=wayland theforceengine`, it crashes. This is the output:
```
[Main] The Force Engine 
v1.09.100

[Paths] Program Path: "/home/paricbat/"
[Paths] Program Data: "/home/paricbat/.local/share/TheForceEngine/"
[Paths] User Documents: "/home/paricbat/.local/share/TheForceEngine/"
[Paths] Source Data: ""
[Startup] TFE_System::init
[Display] Fullscreen enabled.
[Display] Vertical Sync enabled.
[Critical : GPU] Cannot initialize GPU/Window.
Failed to initialize GLEW
```
And if I run  `SDL_VIDEODRIVER=x11 theforceengine`, it does not crash.
This seems to be an issue with glew, here's their issue: nigels-com/glew#172

**Comment by mlauss2** [comment]
Well, this is not a TFE bug, since TFE leaves all the windowing stuff to SDL2.
You probably need to build a GLEW for wayland and adjust LD_LIBRARY_PATH to point to this wayland libglew.so before you start tfe with SDL_VIDEODRIVER=wayland

**Comment by luciusDXL** [comment]
This is not a TFE bug, so I'm going to close.
