### ISSUE TITLE
Ventilation tunnel crate in the first level is indestructible

### ISSUE THREAD

**Issue by Havner** [luciusDXL/TheForceEngine#280]
Ventilation tunnel crate accessible at the end of the first level behind which there is a life is indestructible when playing TFE. Theis is exactly above the place where the player starts this level. When you look up you see a life. This life is available at the end of the level. But not on TFE as you cannot destroy that crate.

**Comment by TP555** [comment]
Hi

You must open the Grid there , and junp in there to get the ExtraLife.

https://www.youtube.com/watch?v=iiBw_hu4aLA&t  5:16 i know there was no Extra Life , isn't Aviable with Hard Diff. , only with Easy or Medium Diff. 

Cheers  !

**Comment by Havner** [comment]
Ok, you're right. I could've sworn you're supposed to destroy that crate in original DF. But it's supposed to be opened. I just checked. Sorry for the confusion.

**Comment by TP555** [comment]
Was also the same on in Original Dos Version 

https://www.youtube.com/watch?v=Ky7fnTZ2f74 9:02  !

Cheers  !
