### ISSUE TITLE
Bloom & Color Correction !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#295]
Hi

Bloom and Color Correction together dosn't work  !
Color Correction Disable the Bloom Effect/s  !

Cheers  !

**Comment by luciusDXL** [comment]
This will be fixed in the next release, there was a logic error when selecting the correct shader for the final blit.

**Comment by TP555** [comment]
Hi

ok , is a bit too Dark without Color Correction , but Reshade does help so long.
But the Bloom Effects looks Great.

Cheers  !

**Comment by luciusDXL** [comment]
Fixed with version 1.09.41
