### ISSUE TITLE
[Feature Request] LAN Multiplayer !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#301]
Hi

I know you had planed before a Online Multiplayer , but you did Cancel this , i think also a Rented Game Server is may too Expensive,
But you can add a LAN Multiplayer Mode  , to Connect with Hamachi or Radmin VPN  ?

Or a Direct IP Connect Option , to play Real Online  ?

Cheers  !

**Comment by luciusDXL** [comment]
I should probably clarify that multiplayer has not been canceled - it is required for Outlaws. However, any Dark Forces based multiplayer cannot happen until Outlaws MP has already been implemented.

**Comment by TP555** [comment]
Hi

ok That are Fine News about the Multiplayer  !

Cheers  !

**Comment by luciusDXL** [comment]
I am going to close this for now - we need to get through Outlaws support first.

**Comment by TP555** [comment]
Hi

Ok thats now Bad News about a Possible Multiplayer
