### ISSUE TITLE
[GPU Renderer] Wall draw on horizon flag

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#303]
Version: 1.09.410-1-g90352998
Game: Dark Forces
Level: Free Kelly https://df-21.net/downloads/missions.php?viewid=1513935647

GPU renderer is drawing a texture that should be just the sky rendering on the wall

GPU Renderer:
![Screenshot 2023-08-03 04-11-05](https://github.com/luciusDXL/TheForceEngine/assets/19301383/bebd9fb7-9e2e-448b-b688-162afd7577e0)

Software Renderer:
![Screenshot 2023-08-03 04-11-17](https://github.com/luciusDXL/TheForceEngine/assets/19301383/05145864-6974-4734-a9d8-fe840d888162)

**Comment by luciusDXL** [comment]
Fixed in master, and the fix will be in the next release.

**Comment by luciusDXL** [comment]
Fixed in the 1.09.5 Release.
