### ISSUE TITLE
(doc) better instruction for linux compilation

### ISSUE THREAD

**Issue by B4rabbas** [luciusDXL/TheForceEngine#305]
Dependencies

sudo apt install y libdevil-dev libasound2-dev

Compile & install rt audio
wget https://www.music.mcgill.ca/~gary/rtaudio/release/rtaudio-5.2.0.tar.gz
tar -xvf rtaudio-5.2.0.tar.gz
cd rtaudio-5.2.0
./configure
make
sudo make install
cd
rm rtaudio-5.2.0.tar.gz
rm -r rtaudio-5.2.0

compile and install rtmidi
wget https://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-5.0.0.tar.gz
tar -xvf rtmidi-5.0.0.tar.gz
cd rtmidi-5.0.0
./configure
make
sudo make install
cd
rm rtmidi-5.0.0.tar.gz
rm -r rtmidi-5.0.0

compile and install TheForceEngine
git clone https://github.com/luciusDXL/TheForceEngine.git
cd TheForceEngine
mkdir tfe-build
cd tfe-build
cmake -S ~/TheForceEngine/
make
sudo make install

make an .desktop :
echo -e "[Desktop Entry]\nType=Application\nName=DarkForce\nExec=theforceengine\nIcon=🔫" | sudo tee /usr/share/applications/darkforce.desktop

**Comment by petran79** [comment]
I get this error

cmake -S ~/TheForceEngine/
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:181 (file):
  file attempted to write a file:
  /home/petros/TheForceEngine/CMakeFiles/CMakeOutput.log into a source
  directory.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by luciusDXL** [comment]
There have been updates to the readme, are the Linux compile steps still unclear?
