### ISSUE TITLE
vueLogic.cpp: Compile error with VS 2022.

### ISSUE THREAD

**Issue by coelckers** [luciusDXL/TheForceEngine#306]
It complains about unknown 'std::modf' in line 580.

This file needs an 

`#include <cmath>`

to compile. Apparently on older versions this got included indirectly somehow.

**Comment by luciusDXL** [comment]
Thanks for the bug report. I will add the include.

**Comment by luciusDXL** [comment]
Fixed in the 1.09.5 Release.
