### ISSUE TITLE
[GPU Renderer] Ramsees Head Ceiling Glitch

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#307]
From limbo on Discord
Game: Dark Forces
Build: 1.09.410
Level: Ramsees Hed

At X: -261 Y: -40.0 Z: 0472 H: 5.8 the ceiling glitches renders the floor texture

GPU: 
![tfe_screenshot_Sat-Aug--5-09_36_05-2023_5](https://github.com/luciusDXL/TheForceEngine/assets/19301383/86ed9025-bb99-4c0d-b4ce-c53bb16f66b9)

Software:
![tfe_screenshot_Sat-Aug--5-09_36_05-2023_6](https://github.com/luciusDXL/TheForceEngine/assets/19301383/10678ccb-4915-4fa5-b978-6c7e3d09bd56)

**Comment by luciusDXL** [comment]
Fixed locally, will be fixed in the next release.

**Comment by luciusDXL** [comment]
Fixed in the 1.09.5 Release.
