### ISSUE TITLE
[Bug] Linux some files in usr/local/share are not loaded 

### ISSUE THREAD

**Issue by RC2225** [luciusDXL/TheForceEngine#309]
Under Linux (At least on my system, on Arch/EndeavorOS)  some support files are not loaded when installed in /usr/local/share. TFE looks for them in the place from where the binary is executed.
 - soundfonts
 - enhanced hud mod
 - credits
 - manual

Shaders, Images and Fonts which are in the same folder are working. 

Output console 
```
[Paths] Program Path: "/home/tim/"
[Paths] Program Data: "/home/tim/.local/share/TheForceEngine/"
[Paths] User Documents: "/home/tim/.local/share/TheForceEngine/"
[Paths] Source Data: "/home/tim/dark/dark_ger/"
```

**Comment by mlauss2** [comment]
Yes, I'll look into this.  For the moment, don't install, just run from the build directory (which simulates the environment the windows binary expects).
