### ISSUE TITLE
Raid on the Ovarid Crash

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#322]
Version: 1.09.410-7-gdead22da
Game: Dark Forces
Mod: Raid on the Ovarid
https://df-21.net/downloads/contests/ovarid.zip

Game crashes during the Phase 1 boarding. Works correctly in DOS

![Screenshot 2023-09-11 01-42-26](https://github.com/luciusDXL/TheForceEngine/assets/19301383/36bb182d-a8fd-41a2-8cce-e8048cfb4ebf)

[ovaridcrash.zip](https://github.com/luciusDXL/TheForceEngine/files/12572585/ovaridcrash.zip)

**Comment by DatMaxNub** [comment]
Very short, but it was the winner of the one room wonder contest. Also the crash doesn't seem to happen now, but the Phase 1s don't even show up.

**Comment by luciusDXL** [comment]
I will debug it soon(tm) - the attackMod should not be null, so I'll have to get to the root cause.

**Comment by mlauss2** [comment]
This one is fixed, yes?  I cannot reproduce the crash any more.
