### ISSUE TITLE
Game Settings screen: green text is cut off at small window sizes

### ISSUE THREAD

**Issue by kevinfoley** [luciusDXL/TheForceEngine#337]
![Game Source Data text cutoff](https://github.com/luciusDXL/TheForceEngine/assets/7231744/052fdae7-5c90-4d26-a943-bdbfd578f7af)

This can be fixed by using `ImGui::TextWrapped()` instead of `ImGui::LabelText()`.

**Comment by luciusDXL** [comment]
Thanks for the report.
