### ISSUE TITLE
First frame of firing weapon after load game.

### ISSUE THREAD

**Issue by Gerwin2k** [luciusDXL/TheForceEngine#342]
I was actually investigating something related, but there is this behavior on my reference system that complicates it.

To verify good vsync and framerate I had this test case with firing weapon at key 6, with the four barrels and green plasma.  Bad Vsync/framerate often prevents the first frame of firing from being visible. The plasma becomes visible only further from the barrel and higher up the screen.  This weapon 6 is the most obvious example of that.

But now I noticed that when I start a new mission there is no issue with that, 
But when I **load a saved game** the issue is always visible.
Start a new game again: no issue.

Can anyone replicate?

**Comment by Gerwin2k** [comment]
Verified to behave as described following systems:

Laptop intel i5-8250U with windows 10 x64, integrated intel graphics
Laptop intel i3-2310M with windows 7 x64, integrated intel graphics
Desktop intel i5-3550 with  windows 7 x64, nVidia Geforce GT 710
Desktop intel i5-3550 with  windows 7 x64, Radeon HD 7750

With official Windows x64 binary v1.09.521. 
Changing rendering settings does not change anything.

**Comment by Gerwin2k** [comment]
Basically, the barrel of the Fusion Cutter weapon (No6) should initially overlap/intersect the fired round/plasma bolt. 
When you start a new game it does that. See attached screenshot. 
When you load a game it never does that. There is always a gap of background visible in between. The composition of the screenshot is skipped.

![cutter_proper](https://github.com/luciusDXL/TheForceEngine/assets/39087372/ed8dc56f-4c23-41c1-b417-4967774a0223)

**Comment by luciusDXL** [comment]
Interesting that there is a different between a new game and loading a saved game. It sounds like some state is not being captured properly. So I will look into it as a bug.

**Comment by Gerwin2k** [comment]
> Sorry for going through this so late.
> 
> It is interesting that there is a difference between a new game and loading a saved game. It sounds like some state is not being captured properly. So I will look into it as a bug and take a look in the near future.

Take your time. 
Since posting this issue, I haven't got any new insights to report.

**Comment by Gerwin2k** [comment]
This should be the commit that fixed this issue, from Mar 27, 2024:
https://github.com/luciusDXL/TheForceEngine/commit/d820c71395b96aa8b90ec9afae5a320283fbf297

**Comment by Gerwin2k** [comment]
Build v1.10.000  (17-07-2024) and tested it. Issue is still there !?

To make sure I also tested the v1.22.200 official windows binary. Issue is still there as well.

Think this ticket should be re-opened.

**Comment by Gerwin2k** [comment]
Did some testing with modified builds, used the Fusion Cutter as the subject to look at.

First to correct the title of this ticket: The weapon fire issue here is not animation frame related, but projectile related.

The weaponFireFunc.cpp under the same circumstances, passes the proper projectile coordinates to projectile.cpp. Both when entering a new game, and also when loading a game. It passes the exact same projectile coordinates, when I log them. 

Next I set the speed of plasma projectiles to 1. This is very slow. And now it shows the origin of the plasma bolts to be near the Fusion Cutter barrels, bot when entering a new game, as well as after loading a game. 

So what seems to be the difference when loading a game, is the timing of rending the projectiles. After loading a game it starts rendering them further out. In other words; later in their existence. I have no idea where to look for the related code.
