### ISSUE TITLE
Better TFE shortcut scheme?

### ISSUE THREAD

**Issue by maxz** [luciusDXL/TheForceEngine#347]
Currently the default shortcut for quicksaving is Alt+F5 and the one for quickloading Alt+F8.

Now I don't know whether I'm incredibly clumsy or whether the shortcut is just positioned badly, but I closed the game more often than I would like to admit (by hitting Alt+F4) when I tried to quicksave in a heated moment.
I know that I can rebind it, but I doubt that I am the only person who hits Alt+F4 instead of Alt+F5, so maybe the default should be changed.

Ctrl+F-Key might work or something else? Basically anything that prevents someone from accidentally pressing Alt+F4 in the heat of battle.
Moving it one row over so that saving is Alt+F8 and loading is Alt+F12 could also work, but I think F5 and F9 is the common scheme.

**Comment by luciusDXL** [comment]
The defaults were setup so that the default Dark Forces F? keys still work as expected. But Ctrl+F5 might be a better default for the reason you mentioned.

**Comment by luciusDXL** [comment]
Save and Load keys can be re-assigned from the Input menu, so I'm going to close this.
