### ISSUE TITLE
[Linux] AppImage release

### ISSUE THREAD

**Issue by kenderipa** [luciusDXL/TheForceEngine#372]
Hello,

are you considering an AppImage release for the upcoming version 1.1? I consider it much better then Flatpak or Snap, since it doesn't pull a sandbox copy of Linux system, is very much portable and should also include all dependencies, thus allowing a user to run a lightweight system unburdened by hundreds of rarely used edge case packages.

**Comment by kenderipa** [comment]
@luciusDXL, what do you think?

**Comment by vrement** [comment]
Flatpak seems (not sure tho) already working on Steam Deck. AppImages are pretty bad for normal users: they would have to chmod +x is to make it executable and also AppImages don't update themselves (user has to download a package over and over again).  Snap is similar self updating etc. and work well nowdays.

**Comment by kenderipa** [comment]
> Flatpak seems (not sure tho) already working on Steam Deck. AppImages are pretty bad for normal users: they would have to chmod +x it to make it executable and also AppImages don't update themselves (user has to download a package over and over again). Snap is similar self updating etc. and work well nowadays. #268

There are several daemons and managers, that make updating AppImages really easy.

**Comment by kenderipa** [comment]
Also, if we're talking about Steam Deck, I think Steam allows AppAimages to be added as non-Steam games. That also probably makes them executable.

**Comment by fpiesche** [comment]
Steam also allows Flatpaks to be added as non-Steam games, to be fair ;) I have put together a Flatpak build that's mostly working and just needs a bit more tweaking that I'd be happy to make public with permission from the repo owners here.

**Comment by nobodywatchin** [comment]
> Steam also allows Flatpaks to be added as non-Steam games, to be fair ;) I have put together a Flatpak build that's mostly working and just needs a bit more tweaking that I'd be happy to make public with permission from the repo owners here.

You should submit it as a PR on here, that would be fantastic!

**Comment by kenderipa** [comment]
Well, there's a third party AppImage now, so closed.
