### ISSUE TITLE
Flatpak not utilizing Dark Forces install in Steam when browsed to the GOB file (crash)

### ISSUE THREAD

**Issue by dziadulewicz** [luciusDXL/TheForceEngine#380]
Was trying to get The Force Engine to launch Dark Forces only to see the whole program shut down when clicking Start. 

The issue appeared to be that the data files of Steam installation of Dark Forces HAD TO BE COPIED to the location of /home/dziadulewicz/.var/app/io.github.theforceengine.tfe/data/ --when apparently the plan was supposedly to just browse on the Dark Forces folder under Steam to get TFE use what's needed and click Start.

Additionally: when The Force Engine was used and tweaked on Steam Deck: there appears no usable or straight forward way to copy paste for example paths to game source data in Settings.

**Comment by vrement** [comment]
The assumed same issue is now dealt in great detail here (closed thread though) https://github.com/luciusDXL/TheForceEngine/issues/268

**Comment by fpiesche** [comment]
The update rolled out to Flathub yesterday should fix this issue. Can you confirm whether this is the case?

**Comment by luciusDXL** [comment]
This should be fixed, so I am closing. Feel free to re-open if it becomes an issue again.
