### ISSUE TITLE
[gamepad] - next/prev weapon toggle with gamepad is too continuous

### ISSUE THREAD

**Issue by BielBdeLuna** [luciusDXL/TheForceEngine#388]
if you're on a gamepad and keep pressing next/prev weapon toggle, the weapon keeps toggling, this can be annoying, maybe this could be changed so that for the next weapon to toggle you should first un-press the weapon toggle you've pressed?
so a press of a next/prev weapon toggle would change to the next/prev weapon only once, even if you keep pressing the button until you un-press and press again.

**Comment by luciusDXL** [comment]
Seems reasonable, I will make the change (from button 'down' to button 'pressed').

**Comment by luciusDXL** [comment]
This will be fixed in the next release.
