### ISSUE TITLE
[Linux] Wine, mouse input choppy

### ISSUE THREAD

**Issue by 12sunflowers** [luciusDXL/TheForceEngine#394]
Hello.
Running TFE under Linux Devuan 5.0 via Wine
Nvidia proprietary driver 340.108
Geforce 9800 gtx(G92) (its old but still good for retro gaming)
Mice (Rival95)
Stable 75 FPS

TFE running good. But when i am using mouselook in game, movement have choppy spikes.
BUT keyboardlook(with no mouse) working perfectly smooth problem only with mouselook.
Was tried Vsync ON/OFF not help.

Can you something suggest?

**Comment by luciusDXL** [comment]
I'm surprised that TFE works with Wine, honestly. I'm not sure what the issue is, honestly.
