### ISSUE TITLE
Cannot compile 1.10 on Mageia 9

### ISSUE THREAD

**Issue by inf78** [luciusDXL/TheForceEngine#428]
After running 'cmake -DDISABLE_SYSMIDI=ON ..'

I get this:
 `CMake Error at CMakeLists.txt:70 (target_link_libraries):
  Target "tfe" links to:

    SDL2::SDL2main

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.`

This doesn't happen with 1.09.540. 'SDL2main' is not a package in Mageia's repos and since it works just fine with the older TFE version and basically any other SDL2 based software, I think it's not a problem in Mageia. SDL2 is 2.26.

When tying to figure out what's the problem, I came across this on SDL2 wiki:

`SDL can be included in your project in 2 major ways:

    using a system SDL library, provided by your (*nix) distribution or a package manager
    using a vendored SDL library: this is SDL copied or symlinked in a subfolder.

The following CMake script supports both, depending on the value of MYGAME_VENDORED.

cmake_minimum_required(VERSION 3.5)
project(mygame)

# Create an option to switch between a system sdl library and a vendored sdl library
option(MYGAME_VENDORED "Use vendored libraries" OFF)

if(MYGAME_VENDORED)
    add_subdirectory(vendored/sdl EXCLUDE_FROM_ALL)
else()
    # 1. Look for a SDL2 package, 2. look for the SDL2 component and 3. fail if none can be found
    find_package(SDL2 REQUIRED CONFIG REQUIRED COMPONENTS SDL2)

    # 1. Look for a SDL2 package, 2. Look for the SDL2maincomponent and 3. DO NOT fail when SDL2main is not available
    find_package(SDL2 REQUIRED CONFIG COMPONENTS SDL2main)
endif()`

Can it be related to it? I mean just to make cmake not fail if SDL2main isn't found?

**Comment by mlauss2** [comment]
Looks like your installed SDL2 is missing the cmake scripts in /usr/share/cmake/SDL2/*
Maybe Mageia didn't package them? or do you have to install a "libsdl2-dev" library like debian/unbuntu?

**Comment by inf78** [comment]
Of course I have the devel installed, as usual. It fails when looking for sdl2main, but I think it shoudn't.

**Comment by mlauss2** [comment]
and does /usr/lib64/libSDL2main.a exist?

**Comment by inf78** [comment]
Interesting. 'libSDL2main.a' is actually present in the static-devel, which I never needed, just like any other static-devels for that matter. From a quick search, older CentOS Stream packaged libSDL2main.a in the static as well, Fedora doesn't it seems.
From just the simple technical point of view, it should be in the static-devel, so I will just keep it installed.
Nonetheless, is the 'libSDL2main.a' lib really a rquirement for TFE?

**Comment by mlauss2** [comment]
Whether it's required depends on the target platform: No on linux, but it might be on others that SDL2 supports. There are 2 PRs open which enable TFE to work on any platform that can also run SDL2 and OpenGL.

**Comment by inf78** [comment]
Ok, thanks.
Seems to be sloved then, at least for me it is.
I'm short on time now, so I will wait a day or so before quickly closing this, just in case.

Thanks for your time again.

**Comment by inf78** [comment]
I understand it in relation to TFE, but the static-devel also contains two other files (libSDL2.a and libSDL2_test.a) and that will likely not pass as an argument to the maintainer. Getting rid of the static-devel and just including all three files in the standard one probably has more of a chance to success, but it will also be an exception to the rule, because those files do belong to the static-devel.
What I think can work though, is making the static-devel a weak dependency of the standard one. I will try to suggest that and see how it goes.

**Comment by mlauss2** [comment]
The libSDL2main.a file is also generated on a dynamic library build.  On Linux, it contains a single function "int SDL_dummy_main() { return 0; }".  But as far as I understood the SDL2 documentation, on some platforms, even if SDL2 is loaded dynamically, this .a file may contain required code that needs to be statically linked into the executable to get sdl going.
So for a -dev package, it should be included regardless of whether static or dynamic linking is attempted.
