### ISSUE TITLE
Verify TFE on Flathub

### ISSUE THREAD

**Issue by fpiesche** [luciusDXL/TheForceEngine#429]
Now that we have a Flatpak release, it'd be nice if we could get it marked as verified on Flathub; they're beginning to prioritise verified apps over unverified ones (as they may be unofficial builds with unauthorised modifications). Would you be okay with doing this, essentially marking the Flathub release as "official" (on the assumption I'll be hanging around like a bad smell to check out problems people have with it specifically)?

If so, verification of the app for Flathub involves deploying a plain text file at `https://theforceengine.github.io/.well-known/org.flathub.VerifiedApps.txt` containing an identification token. The token is `6761583b-3161-45b8-9c3f-1a7c7438fc67` - as this will go into a publicly accessible file with a known name and the token is entirely for Flathub to connect and verify that we control the site it's safe to share in public.

I'd have happily created a PR to do this but the GitHub page is not on a public repo so I can't.

**Comment by luciusDXL** [comment]
The file should be in place now.

**Comment by fpiesche** [comment]
and there it is! ![image](https://github.com/user-attachments/assets/41655d6f-fece-4638-9e59-da0eea865185)
