### ISSUE TITLE
[🐛] FOV UI mess

### ISSUE THREAD

**Issue by JakeSmarter** [luciusDXL/TheForceEngine#431]
Linux Flathub v1.10.000-28-ge19bcde1+

The FOV UI controls seem to be divided into horizontal and vertical FOV. However, it is unclear which one is which. :confused:
H-FOV and V-FOV seem to be coupled but one is a slider and the other a spinner. It is also unclear why one is a slider and the other a spinner. Furthermore, the slider has a value range from `020` to `160` but the spinner from `5` to `175`. And, because these controls are coupled you can effectively set both from `5` to `175` by using the spinner only. It is also unclear why the slider always renders three digit values with leading `0`s although these are simple degree values. :face_with_spiral_eyes:

If for some good reason H-FOV and V-FOV have to be coupled anyway, lets stop distinguishing between them but combine them in just UI control for both and go with the shortest range limit. Because as it is right now, it is very confusing. :face_with_head_bandage:

**Comment by mlauss2** [comment]
So in essence the slider and the spinner don't have the same range.  hardly a "mess", and easy to fix.

**Comment by luciusDXL** [comment]
I'm confused, both the slider and input map to the same FOV. There are two inputs so you can either use the slider or manually enter the number.

**Comment by luciusDXL** [comment]
There is only one value - just two ways of adjusting it, the slider and the edit.

**Comment by luciusDXL** [comment]
Here is an example from another tool.
![image](https://github.com/user-attachments/assets/18f1cba2-7322-4d9f-8944-525c989cb8aa)

There is a slider and an edit box. The slider is nice because you see the value smoothly changing, and the edit box is nice because you can set precise values.

**Comment by luciusDXL** [comment]
I'd rather not argue over UI design. If people legitimately find it confusing or annoying, I will just remove the slider. I suppose if one person finds it confusing or annoying, than others do as well. I was just surprised by the strong reaction since its the first complaint I've had about it.

It will be gone in the next release, so I'm going to close the issue.
![image](https://github.com/user-attachments/assets/0deab4a2-1f7f-4d30-b79f-0dcb9f080e78)
