### ISSUE TITLE
mesa Shader compiler error

### ISSUE THREAD

**Issue by mlauss2** [luciusDXL/TheForceEngine#439]
@luciusDXL please add a newline at the end of file Shaders/curve.h, fixes this mesa shader compiler complaint:

```
[Error : Shader] Failed to compile 'Shaders/line2d.frag'!

[Error : Shader] Error: 0:130(2): preprocessor error: syntax error, unexpected HASH_TOKEN
0:7(1): preprocessor error: Unterminated #if

```

**Comment by luciusDXL** [comment]
They already have new lines at the end, I will try adding another.

**Comment by mlauss2** [comment]
@luciusDXL :  the curve.h one was the missing one.  fixed now.
