### ISSUE TITLE
Exit suddenly unexpected and problems with the agents at the beginning of dark forces

### ISSUE THREAD

**Issue by darkstar252** [luciusDXL/TheForceEngine#447]
When you want to put an agent in the first screen an you put the name. At the right you see garbage instead of your agent name, and that name and his missions were not saved.
 
NOTE ON THIS: Using the game as normal user it puts me this :

[Error : Agent] Cannot open DarkPilo.cfg
 
But thie file is in there and with the given permissions:

[darkstar@WOPR tfe]$ ls -lai
total 34476
16283411 drwxr-xr-x 14 darkstar darkstar     4096 sep 18 00:31 .
16256617 drwxr-xr-x 13 darkstar darkstar     4096 sep  8 21:25 ..
16283431 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 Captions
16283577 -rw-rw-rw-  1 darkstar darkstar 14244049 mar 22  1995 dark.gob
16283585 -rw-rw-rw-  1 darkstar darkstar    10425 dic 14  1994 darkpilo.cfg
16284585 -rw-rw-rw-  1 darkstar darkstar    10425 sep 18 00:31 DarkPìlo.cfg
16283424 drwxr-xr-x  4 darkstar darkstar     4096 dic 14  2023 Documentation
16283560 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 Fonts
16283578 -rw-rw-rw-  1 darkstar darkstar      258 feb  9  1995 jedi.cfg
16283466 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 lfd
16283576 -rw-rw-rw-  1 darkstar darkstar     2989 feb  9  1995 local.msg
16283412 drwxr-xr-x  3 darkstar darkstar     4096 dic 14  2023 Mods
16283586 drwxr-xr-x  2 darkstar darkstar     4096 ago 18 20:54 Saves
16283587 drwxr-xr-x  2 darkstar darkstar     4096 ago 18 20:54 Screenshots
16283511 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 Shaders
16283556 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 SoundFonts
16283582 -rw-rw-rw-  1 darkstar darkstar  5950117 feb 14  1995 sounds.gob
16283126 -rw-rw-rw-  1 darkstar darkstar  2816419 feb 14  1995 sprites.gob
16283588 drwxr-xr-x  2 darkstar darkstar     4096 ago 18 20:54 Temp
16283583 -rw-rw-rw-  1 darkstar darkstar  8929232 feb 14  1995 textures.gob
16283581 -rwxrwxrwx  1 darkstar darkstar  3248784 dic 14  2023 theforceengine
16283580 -rw-rw-rw-  1 darkstar darkstar      249 dic 14  2023 TheForceEngine.desktop
16283579 -rw-rw-rw-  1 darkstar darkstar    11219 dic 14  2023 TheForceEngine.png
16283438 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 UI_Images
16283435 drwxr-xr-x  2 darkstar darkstar     4096 dic 14  2023 UI_Text

Even if you can play the game an autosave the levels , this is not good while you run the game using start and the agent does not appear and the latest mission.

The other and annoying problem is when you have 0 lives and you're completed dead the program exits without any warning or nothing.

**Comment by ifeldshteyn** [comment]
What is your environment? What is the TFE version and are you on nix/windows? Do you have any crashes? If so can you post the dump/log here or in discord? Can you send a screenshot of the garbage in the menu?

**Comment by darkstar252** [comment]
ohh thanks for the fast response i am using Manjaro Linux with linux kernel:

Linux WOPR 6.10.6-10-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:17:40 UTC 2024 x86_64 GNU/Linux

[Main] The Force Engine
v1.09.530-13-gd029fe2b

[Paths] Program Path: "/home/darkstar/apps/games/tfe/"
[Paths] Program Data: "/home/darkstar/.local/share/TheForceEngine/"
[Paths] User Documents: "/home/darkstar/.local/share/TheForceEngine/"
[Paths] Source Data: "/home/darkstar/apps/games/tfe/"
[Startup] TFE_System::init
[Display] Fullscreen enabled.
[Display] Vertical Sync enabled.
[RenderBackend] OpenGL Device Tier: 3
[Startup] TFE_AudioSystem::init
[Audio] SDLAudio using interface 'pulseaudio'
[Audio] Device 00: GP106 High Definition Audio Controller Estéreo digital (HDMI)
[Audio] Device 01: Starship/Matisse HD Audio Controller Estéreo analógico
[Audio] Starting up audio stream for device '<autoselect>'
[Startup] TFE_MidiPlayer::init
[Startup] TFE_Polygon::init
[Startup] TFE_Image::init
[Startup] TFE_FrontEndUI::init
[MemoryRegion] Allocated new memory block in region 'game' - new size is 1 blocks, total size is '8388608'
[MemoryRegion] Allocated new memory block in region 'level' - new size is 1 blocks, total size is '8388608'
[Progam Flow] The Force Engine Game Loop Started
[Game] Dark Forces Version: 1.0 (Build 1)
[Error : Agent] Cannot open DarkPilo.cfg
[MemoryRegion] Allocated new memory block in region 'Landru' - new size is 1 blocks, total size is '4194304'
[MemoryRegion] Allocated new memory block in region 'Cutscene' - new size is 1 blocks, total size is '8388608'
[Error : Agent] Cannot open DarkPilo.cfg

**Comment by darkstar252** [comment]
I compile the newest release 1.09 and it does not exit the program suddenly when you haven't got any lives.
