### ISSUE TITLE
Support LVB file format

### ISSUE THREAD

**Issue by luciusDXL** [luciusDXL/TheForceEngine#63]
Support for LVB file format for the Dark Forces demo. A variant of this format is also required for Outlaws.

**Comment by njankowski** [comment]
I took apart some of these file formats a while ago.
No guarantees on correctness, but it might be useful to cross-reference against your own RE work.
https://github.com/njankowski/dftools/tree/master/doc

Thanks for doing this by the way.
This is a great piece of history that deserves attention.

**Comment by luciusDXL** [comment]
Thanks for the information njankowski. I will take a look.

**Comment by luciusDXL** [comment]
Fixed in the 1.09.5 Release.
