### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by siredmar** [luciusDXL/TheForceEngine#81]
Hi!

Look at this project here: https://github.com/pavelliavonau/cmakeconverter

it converts the Visual Studio sln file to CMake. 
I tried it myself and got angelscript to compile, however TheForceEngine uses some Windows Headers
```
TheForceEngine/TheForceEngine/targetver.h:8:10: fatal error: SDKDDKVer.h: No such file or directory
 #include <SDKDDKVer.h>
```

If you can get rid of those Windows only dependeicies, it might compile just fine under Linux.

**Comment by luciusDXL** [comment]
I am planning on putting together a CMake project later, I just haven't gotten to it yet.
