### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by winterheart** [luciusDXL/TheForceEngine#92]
Hello.

I've tried to compile project on Win10 with VS 2019, but, while it compiles with some trivial fixes, it's fails with exception on creating vertex buffer. How can I get to run it? Is there some instructions to get it work? Is current master is runnable at all?

**Comment by luciusDXL** [comment]
It is strange that master is broken. I am in the middle of working on the next test release which will be a big step forward - once that is done I will verify that master is compiling as intended. If you want to try out what is already there, you can get the binaries from https://theforceengine.github.io/downloads.html - Pre-Release Build Version 0.01.006-1; Win64 and Experimental Builds; Win64 are the most up-to-date.
