### ISSUE TITLE
3D Sound ?

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#94]
Hi

i did try Force 3D Sound with DSOAL or OpenAL Soft. , but it dosn't work , or no Log File will Created from DSOAL & OpenAL Soft. with Follow Commands.

set DSOAL_LOGLEVEL=3
set DSOAL_LOGFILE= Name

set ALSOFT_LOGLEVEL=3
set ALSOFT_LOGFILE= Name

i have look in the Files , a dsound.dll which use i have find in the sdl2.dll , seems a dsound.dll will be used , but DSOAL will not work.

or is there a another problem , it will be prefer the dsound,dll from System32 , and not the dsound.dll from DSOAL in the Root Gamedir where the TheForceEngine.exe is located. ?

The Current The Force Engine Version  0.02.001-129-gbc44570 is only 64Bit  ?

I know , Sound is under Construction , but it use a dsound.dll  , so i don't understand why it won't work with DSOAL dsound.dll !
No Log File , No Error of course , or a try to communicate with DSOAL !

**Comment by luciusDXL** [comment]
The Force Engine does not use OpenAL or SDL for sound. SDL is used for other things though, which is why it is included. TFE uses a low-level sound system and implements sound mixing and 3D sound internally to better match the original games.
