### ISSUE TITLE
FPS Drops with Higher Res.  !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#95]
Hi

im get some FPS Drops with Higher Res. on Close Walls with Objects  !!

https://www.youtube.com/watch?v=gdJHj7elJQw

Update : Same issue in Core Release 0.70.000 !

**Comment by luciusDXL** [comment]
As dicussed on the forums, this is not a bug. The hardware renderer should solve the performance issue once it is complete.
