### ISSUE TITLE
Unable To Bind Commands To Mouse Wheel

### ISSUE THREAD

**Issue by TheKins** [luciusDXL/TheForceEngine#96]
See title. This would be useful for the "Next Weapon" and "Previous Weapon" keybinds, but as things stand the key-binding interface doesn't seem to detect it.

**Comment by TP555** [comment]
Hi

@TheKins

Better you Post your Issue , in the Forum.
Here seems less or none Activity , in the Forum very much  :D

https://the-force-engine.freeforums.net/board/4/bugs

Cheers !

**Comment by luciusDXL** [comment]
I have been meaning to get to this, thanks for the reminder.
